package com.sales.dao;

import java.util.List;

import com.sales.model.SCarRepairApplication;

public interface SCarRepairApplicationDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_car_repair_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    Integer insert(SCarRepairApplication record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_car_repair_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKey(SCarRepairApplication record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_car_repair_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKeySelective(SCarRepairApplication record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_car_repair_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    SCarRepairApplication selectByPrimaryKey(Integer carApplicationId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_car_repair_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int deleteByPrimaryKey(Integer carApplicationId);
    
    List<SCarRepairApplication> getCarApplicationListPage(SCarRepairApplication ca);
    
    Integer getCarApplicationListPageCount(SCarRepairApplication ca);
    
    List<SCarRepairApplication> getCarApplicationListForReimbursement(Integer userId);
    
    public String getMaxCode();
}