package com.sales.dao;

import java.util.List;

import com.sales.model.SCustomerProject;

public interface SCustomerProjectDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_project
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    void insert(SCustomerProject record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_project
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    int updateByPrimaryKey(SCustomerProject record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_project
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    int updateByPrimaryKeySelective(SCustomerProject record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_project
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    SCustomerProject selectByPrimaryKey(Integer projectId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_project
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    int deleteByPrimaryKey(Integer projectId);
    
    public List<SCustomerProject> getCustomerProjectListByCustomerId(Integer customerId);
    
    public List<SCustomerProject> selectCPlist(Long pageNumber, int pageSize, 
    		SCustomerProject project);
	public Integer getCustomerProjectCount(SCustomerProject project);
	public List<SCustomerProject> selectCPlistByCustomerIds(Long pageNumber, int pageSize, 
			SCustomerProject project, String customerIds);
	public Integer getCPCountByCustomerIds(SCustomerProject project, String customerIds);
}