package com.sales.dao;

import java.util.List;

import com.sales.model.SCustomerUser;

public interface SCustomerUserDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_user
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    void insert(SCustomerUser record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_user
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKey(SCustomerUser record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_user
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKeySelective(SCustomerUser record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_user
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    SCustomerUser selectByPrimaryKey(Integer customerUserId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_user
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int deleteByPrimaryKey(Integer customerUserId);
    
    public List<SCustomerUser> getCustomerUserListByUserId(Integer userId);
    
    public List<SCustomerUser> getCustomerUserListByCustomerId(Integer customerId);
    
    public List<SCustomerUser> selectCustomerUserList(Long pageNumber, int pageSize, SCustomerUser customerUser);
	public Integer getCustomerUserCount(SCustomerUser customerUser);
	
	public void deleteByCustomerId(Integer customerId, Integer userId);
}