package com.sales.dao;

import com.sales.model.SCustomerFinEvaluation;

public interface SCustomerFinEvaluationDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_fin_evaluation
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    void insert(SCustomerFinEvaluation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_fin_evaluation
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    int updateByPrimaryKey(SCustomerFinEvaluation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_fin_evaluation
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    int updateByPrimaryKeySelective(SCustomerFinEvaluation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_fin_evaluation
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    SCustomerFinEvaluation selectByPrimaryKey(Integer evaId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_fin_evaluation
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    int deleteByPrimaryKey(Integer evaId);
    
    public void deleteByCustomerId(Integer customerId);
    
    public SCustomerFinEvaluation selectByCustomerId(Integer customerId);
}