package com.sales.dao;

import com.sales.model.SCustomerLevel;

public interface SCustomerLevelDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_level
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    void insert(SCustomerLevel record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_level
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    int updateByPrimaryKey(SCustomerLevel record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_level
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    int updateByPrimaryKeySelective(SCustomerLevel record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_level
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    SCustomerLevel selectByPrimaryKey(Integer customerLevelId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_level
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    int deleteByPrimaryKey(Integer customerLevelId);
    
    public void deleteByCustomerId(Integer customerId);
    
    public SCustomerLevel selectByCustomerId(Integer customerId);
}