package com.sales.dao;

import com.sales.model.SCustomerEvaluation;

public interface SCustomerEvaluationDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_cusromer_evaluation
     *
     * @abatorgenerated Thu Jun 27 16:52:56 CST 2013
     */
    void insert(SCustomerEvaluation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_cusromer_evaluation
     *
     * @abatorgenerated Thu Jun 27 16:52:56 CST 2013
     */
    int updateByPrimaryKey(SCustomerEvaluation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_cusromer_evaluation
     *
     * @abatorgenerated Thu Jun 27 16:52:56 CST 2013
     */
    int updateByPrimaryKeySelective(SCustomerEvaluation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_cusromer_evaluation
     *
     * @abatorgenerated Thu Jun 27 16:52:56 CST 2013
     */
    SCustomerEvaluation selectByPrimaryKey(Integer evaId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_cusromer_evaluation
     *
     * @abatorgenerated Thu Jun 27 16:52:56 CST 2013
     */
    int deleteByPrimaryKey(Integer evaId);
}