package com.sales.dao;

import java.util.List;

import com.sales.model.SExpenseApplication;

public interface SExpenseApplicationDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_expense_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    Integer insert(SExpenseApplication record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_expense_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKey(SExpenseApplication record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_expense_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKeySelective(SExpenseApplication record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_expense_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    SExpenseApplication selectByPrimaryKey(Integer expenseApplicationId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_expense_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int deleteByPrimaryKey(Integer expenseApplicationId);
    
    public List<SExpenseApplication> getExpenseApplicationListPage(SExpenseApplication ea);
	
	public Integer getExpenseApplicationListPageCount(SExpenseApplication ea);
	
	public List<SExpenseApplication> getExpenseApplicationListForReimbursement(Integer userId);
	
	public String getMaxCode();
}