package com.sales.dao;

import java.util.List;

import com.sales.model.SLog;

public interface SLogDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_log
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    void insert(SLog record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_log
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKey(SLog record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_log
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKeySelective(SLog record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_log
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    SLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_log
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int deleteByPrimaryKey(Integer logId);
    
    public List<SLog> getLogListPage(SLog log);

	public Integer getLogListPageCount(SLog log);
}