package com.sales.dao;

import com.sales.model.SMethod;

public interface SMethodDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_method
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    void insert(SMethod record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_method
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKey(SMethod record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_method
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKeySelective(SMethod record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_method
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    SMethod selectByPrimaryKey(Integer methodId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_method
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int deleteByPrimaryKey(Integer methodId);
}