package com.sales.dao;

import com.sales.model.SOvertimeCollection;

public interface SOvertimeCollectionDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_overtime_collection
     *
     * @abatorgenerated Thu Jul 11 20:43:32 CST 2013
     */
    void insert(SOvertimeCollection record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_overtime_collection
     *
     * @abatorgenerated Thu Jul 11 20:43:32 CST 2013
     */
    int updateByPrimaryKey(SOvertimeCollection record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_overtime_collection
     *
     * @abatorgenerated Thu Jul 11 20:43:32 CST 2013
     */
    int updateByPrimaryKeySelective(SOvertimeCollection record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_overtime_collection
     *
     * @abatorgenerated Thu Jul 11 20:43:32 CST 2013
     */
    SOvertimeCollection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_overtime_collection
     *
     * @abatorgenerated Thu Jul 11 20:43:32 CST 2013
     */
    int deleteByPrimaryKey(Integer id);
}