package com.sales.dao;

import java.util.List;

import com.sales.model.SOvertime;

public interface SOvertimeDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_overtime
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    Integer insert(SOvertime record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_overtime
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKey(SOvertime record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_overtime
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKeySelective(SOvertime record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_overtime
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    SOvertime selectByPrimaryKey(Integer overtimeId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_overtime
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int deleteByPrimaryKey(Integer overtimeId);
    
    public List<SOvertime> getOvertimeListPage(SOvertime overtime);

	public Integer getOvertimeListPageCount(SOvertime overtime);
	
	public String getMaxCode();
}