package com.sales.dao;

import java.util.List;

import com.sales.model.SParameter;
import com.sales.service.SParameterService;

public interface SParameterDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_parameter
     *
     * @abatorgenerated Thu May 23 22:17:00 CST 2013
     */
    void insert(SParameter record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_parameter
     *
     * @abatorgenerated Thu May 23 22:17:00 CST 2013
     */
    int updateByPrimaryKey(SParameter record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_parameter
     *
     * @abatorgenerated Thu May 23 22:17:00 CST 2013
     */
    int updateByPrimaryKeySelective(SParameter record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_parameter
     *
     * @abatorgenerated Thu May 23 22:17:00 CST 2013
     */
    SParameter selectByPrimaryKey(Integer parameterId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_parameter
     *
     * @abatorgenerated Thu May 23 22:17:00 CST 2013
     */
    int deleteByPrimaryKey(Integer parameterId);
    
    public List<SParameter> getParameterListPage(SParameter param);
	
	public Integer getParameterListPageCount(SParameter param);
	
	/**
	 * 通过配置参数获取
	 * @param parameterName
	 * @return
	 */
	public SParameter selectByName(String parameterName);
}