package com.sales.dao;

import java.util.Date;
import java.util.List;

import com.sales.model.SPerformanceSql;

public interface SPerformanceSqlDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_sql
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    void insert(SPerformanceSql record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_sql
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKey(SPerformanceSql record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_sql
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKeySelective(SPerformanceSql record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_sql
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    SPerformanceSql selectByPrimaryKey(Integer sqlId);
    
    SPerformanceSql selectByPrimaryName(String name);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_sql
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int deleteByPrimaryKey(Integer sqlId);
    
    public List<SPerformanceSql> getSqlList();
    
    public int calSqlScore(String sql, String userIds, Date startDate, Date endDate);
}