package com.sales.dao;

import java.util.List;

import com.sales.model.SPerformancePlan;

public interface SPerformancePlanDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int insert(SPerformancePlan record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKey(SPerformancePlan record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKeySelective(SPerformancePlan record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    SPerformancePlan selectByPrimaryKey(Integer planId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int deleteByPrimaryKey(Integer planId);
    
    public List<SPerformancePlan> getPlanListPage(SPerformancePlan spp);
    
    public Integer getPlanListPageCount(SPerformancePlan spp);
}