package com.sales.dao;

import java.util.List;

import com.sales.model.SPerformanceItem;

public interface SPerformanceItemDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    void insert(SPerformanceItem record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKey(SPerformanceItem record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKeySelective(SPerformanceItem record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    SPerformanceItem selectByPrimaryKey(Integer itemId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int deleteByPrimaryKey(Integer itemId);
    
    public List<SPerformanceItem> getItemListPage(SPerformanceItem spi);
    
    public Integer getItemListPageCount(SPerformanceItem spi);
    
    public List<SPerformanceItem> getPlanItemList(Integer planId);
}