package com.sales.dao;

import java.util.List;

import com.sales.model.SPlanItem;

public interface SPlanItemDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_plan_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    void insert(SPlanItem record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_plan_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKey(SPlanItem record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_plan_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKeySelective(SPlanItem record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_plan_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    SPlanItem selectByPrimaryKey(Integer planItemId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_plan_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int deleteByPrimaryKey(Integer planItemId);
    
    public List<SPlanItem> getPlanItemListByConditions(SPlanItem spi);
    
    public void deleteByPlanId(Integer planId);
}