package com.sales.dao;

import com.sales.model.SPlanStation;

public interface SPlanStationDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_plan_station
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    void insert(SPlanStation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_plan_station
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKey(SPlanStation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_plan_station
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int updateByPrimaryKeySelective(SPlanStation record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_plan_station
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    SPlanStation selectByPrimaryKey(Integer planStationId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_plan_station
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    int deleteByPrimaryKey(Integer planStationId);
}