package com.sales.dao;

import java.util.List;

import com.sales.model.SRole;
import com.sales.model.SUser;

public interface SRoleDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    void insert(SRole record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int updateByPrimaryKey(SRole record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int updateByPrimaryKeySelective(SRole record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    SRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int deleteByPrimaryKey(Integer roleId);
    
    List<SRole> getRoleList();
    
    /**
     * 获取指定岗位的用户列表
     * @param positionId
     * @return
     */
    public List<SUser> getUsers(Integer positionId);
}