package com.sales.dao;

import java.util.List;

import com.sales.model.SRoleAction;

public interface SRoleActionDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role_action
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    void insert(SRoleAction record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role_action
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int updateByPrimaryKey(SRoleAction record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role_action
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int updateByPrimaryKeySelective(SRoleAction record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role_action
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    SRoleAction selectByPrimaryKey(Integer roleActionId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role_action
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int deleteByPrimaryKey(Integer roleActionId);
    
    public List<SRoleAction> getRoleActionListByRoleId(Integer roleId);
    
    public void deleteByRoleId(Integer roleId);
}