package com.sales.dao;

import com.sales.model.STraining;

public interface STrainingDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_training
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    void insert(STraining record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_training
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int updateByPrimaryKey(STraining record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_training
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int updateByPrimaryKeySelective(STraining record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_training
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    STraining selectByPrimaryKey(Integer trainingId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_training
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int deleteByPrimaryKey(Integer trainingId);
}