package com.sales.dao;

import java.util.List;

import com.sales.model.STripApplication;

public interface STripApplicationDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_application
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
	Integer insert(STripApplication record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_application
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int updateByPrimaryKey(STripApplication record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_application
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int updateByPrimaryKeySelective(STripApplication record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_application
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    STripApplication selectByPrimaryKey(Integer tripId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_application
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int deleteByPrimaryKey(Integer tripId);
    
    public List<STripApplication> getTripApplicationListPage(STripApplication ta);
	
	public Integer getTripApplicationListPageCount(STripApplication ta);
	
	public List<STripApplication> getTripApplicationListForReimbursement(Integer userId);
	
	public String getMaxCode();
}