package com.sales.dao;

import com.sales.model.STripExpense;

public interface STripExpenseDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_expense
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    void insert(STripExpense record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_expense
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int updateByPrimaryKey(STripExpense record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_expense
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int updateByPrimaryKeySelective(STripExpense record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_expense
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    STripExpense selectByPrimaryKey(Integer tripExpenseId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_expense
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int deleteByPrimaryKey(Integer tripExpenseId);
}