package com.sales.dao;

import java.util.List;

import com.sales.model.SUserPerformanceItem;
import com.sales.model.SUserPerformancePlan;

public interface SUserPerformanceItemDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    void insert(SUserPerformanceItem record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int updateByPrimaryKey(SUserPerformanceItem record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int updateByPrimaryKeySelective(SUserPerformanceItem record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    SUserPerformanceItem selectByPrimaryKey(Integer performanceItemId);
    

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    int deleteByPrimaryKey(Integer performanceItemId);
    
    public void deleteByUserPlanId(Integer userPlanId);
    
    public List<SUserPerformanceItem> getUserItemListPage(SUserPerformanceItem upi);
    
    public Integer getUserItemListPageCount(SUserPerformanceItem upi);
}