package com.sales.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.sales.dao.SCarRepairApplicationDAO;
import com.sales.model.SCarRepairApplication;

public class SCarRepairApplicationDAOImpl extends SqlMapClientDaoSupport implements SCarRepairApplicationDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_car_repair_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public SCarRepairApplicationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_car_repair_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer insert(SCarRepairApplication record) {
        return (Integer) getSqlMapClientTemplate().insert("s_car_repair_application.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_car_repair_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int updateByPrimaryKey(SCarRepairApplication record) {
        int rows = getSqlMapClientTemplate().update("s_car_repair_application.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_car_repair_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int updateByPrimaryKeySelective(SCarRepairApplication record) {
        int rows = getSqlMapClientTemplate().update("s_car_repair_application.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_car_repair_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public SCarRepairApplication selectByPrimaryKey(Integer carApplicationId) {
        SCarRepairApplication key = new SCarRepairApplication();
        key.setCarApplicationId(carApplicationId);
        SCarRepairApplication record = (SCarRepairApplication) getSqlMapClientTemplate().queryForObject("s_car_repair_application.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_car_repair_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int deleteByPrimaryKey(Integer carApplicationId) {
        SCarRepairApplication key = new SCarRepairApplication();
        key.setCarApplicationId(carApplicationId);
        int rows = getSqlMapClientTemplate().delete("s_car_repair_application.deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public List<SCarRepairApplication> getCarApplicationListPage(SCarRepairApplication ca) {
		return getSqlMapClientTemplate().queryForList("s_car_repair_application.getCarApplicationListPage", ca);
	}

	@Override
	public Integer getCarApplicationListPageCount(SCarRepairApplication ca) {
		return (Integer) getSqlMapClientTemplate().queryForObject("s_car_repair_application.getCarApplicationListPageCount", ca);
	}

	@Override
	public List<SCarRepairApplication> getCarApplicationListForReimbursement(Integer userId) {
		return getSqlMapClientTemplate().queryForList("s_car_repair_application.getCarApplicationListForReimbursement", userId);
	}

	@Override
	public String getMaxCode() {
		Object obj = getSqlMapClientTemplate().queryForObject("s_car_repair_application.getMaxCode");
		if (obj != null) {
		    return (String) obj;
		}
		return null;
	}
}