package com.sales.dao.impl;

import com.sales.dao.SCustomerLevelDAO;
import com.sales.model.SCustomerLevel;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SCustomerLevelDAOImpl extends SqlMapClientDaoSupport implements SCustomerLevelDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_level
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    public SCustomerLevelDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_level
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    public void insert(SCustomerLevel record) {
        getSqlMapClientTemplate().insert("s_customer_level.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_level
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    public int updateByPrimaryKey(SCustomerLevel record) {
        int rows = getSqlMapClientTemplate().update("s_customer_level.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_level
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    public int updateByPrimaryKeySelective(SCustomerLevel record) {
        int rows = getSqlMapClientTemplate().update("s_customer_level.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_level
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    public SCustomerLevel selectByPrimaryKey(Integer customerLevelId) {
        SCustomerLevel key = new SCustomerLevel();
        key.setCustomerLevelId(customerLevelId);
        SCustomerLevel record = (SCustomerLevel) getSqlMapClientTemplate().queryForObject("s_customer_level.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_level
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    public int deleteByPrimaryKey(Integer customerLevelId) {
        SCustomerLevel key = new SCustomerLevel();
        key.setCustomerLevelId(customerLevelId);
        int rows = getSqlMapClientTemplate().delete("s_customer_level.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public void deleteByCustomerId(Integer customerId) {
		// TODO Auto-generated method stub
		getSqlMapClientTemplate().delete("s_customer_level.deleteByCustomerId", customerId);
	}

	@Override
	public SCustomerLevel selectByCustomerId(Integer customerId) {
		// TODO Auto-generated method stub
		SCustomerLevel record = (SCustomerLevel) getSqlMapClientTemplate().queryForObject("s_customer_level.selectByCustomerId", customerId);
        return record;
	}
}