package com.sales.dao.impl;

import com.sales.dao.SCustomerFinEvaluationDAO;
import com.sales.model.SCustomerFinEvaluation;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SCustomerFinEvaluationDAOImpl extends SqlMapClientDaoSupport implements SCustomerFinEvaluationDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_fin_evaluation
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public SCustomerFinEvaluationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_fin_evaluation
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public void insert(SCustomerFinEvaluation record) {
        getSqlMapClientTemplate().insert("s_customer_fin_evaluation.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_fin_evaluation
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public int updateByPrimaryKey(SCustomerFinEvaluation record) {
        int rows = getSqlMapClientTemplate().update("s_customer_fin_evaluation.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_fin_evaluation
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public int updateByPrimaryKeySelective(SCustomerFinEvaluation record) {
        int rows = getSqlMapClientTemplate().update("s_customer_fin_evaluation.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_fin_evaluation
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public SCustomerFinEvaluation selectByPrimaryKey(Integer evaId) {
        SCustomerFinEvaluation key = new SCustomerFinEvaluation();
        key.setEvaId(evaId);
        SCustomerFinEvaluation record = (SCustomerFinEvaluation) getSqlMapClientTemplate().queryForObject("s_customer_fin_evaluation.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_customer_fin_evaluation
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public int deleteByPrimaryKey(Integer evaId) {
        SCustomerFinEvaluation key = new SCustomerFinEvaluation();
        key.setEvaId(evaId);
        int rows = getSqlMapClientTemplate().delete("s_customer_fin_evaluation.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }
    
    public void deleteByCustomerId(Integer customerId){
    	getSqlMapClientTemplate().delete("s_customer_fin_evaluation.deleteByCustomerId",customerId);
    }

	@Override
	public SCustomerFinEvaluation selectByCustomerId(Integer customerId) {
		// TODO Auto-generated method stub
		SCustomerFinEvaluation record = (SCustomerFinEvaluation) getSqlMapClientTemplate().queryForObject("s_customer_fin_evaluation.selectByCustomerId", customerId);
        return record;
	}
}