package com.sales.dao.impl;

import java.util.List;

import com.sales.dao.SExpenseApplicationDAO;
import com.sales.model.SExpenseApplication;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SExpenseApplicationDAOImpl extends SqlMapClientDaoSupport implements SExpenseApplicationDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_expense_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public SExpenseApplicationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_expense_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer insert(SExpenseApplication record) {
        return (Integer) getSqlMapClientTemplate().insert("s_expense_application.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_expense_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int updateByPrimaryKey(SExpenseApplication record) {
        int rows = getSqlMapClientTemplate().update("s_expense_application.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_expense_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int updateByPrimaryKeySelective(SExpenseApplication record) {
        int rows = getSqlMapClientTemplate().update("s_expense_application.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_expense_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public SExpenseApplication selectByPrimaryKey(Integer expenseApplicationId) {
        SExpenseApplication key = new SExpenseApplication();
        key.setExpenseApplicationId(expenseApplicationId);
        SExpenseApplication record = (SExpenseApplication) getSqlMapClientTemplate().queryForObject("s_expense_application.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_expense_application
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int deleteByPrimaryKey(Integer expenseApplicationId) {
        SExpenseApplication key = new SExpenseApplication();
        key.setExpenseApplicationId(expenseApplicationId);
        int rows = getSqlMapClientTemplate().delete("s_expense_application.deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public List<SExpenseApplication> getExpenseApplicationListPage(SExpenseApplication ea) {
		return getSqlMapClientTemplate().queryForList("s_expense_application.getExpenseApplicationListPage", ea);
	}

	@Override
	public Integer getExpenseApplicationListPageCount(SExpenseApplication ea) {
		return (Integer) getSqlMapClientTemplate().queryForObject("s_expense_application.getExpenseApplicationListPageCount", ea);
	}

	@Override
	public List<SExpenseApplication> getExpenseApplicationListForReimbursement(Integer userId) {
		return getSqlMapClientTemplate().queryForList("s_expense_application.getExpenseApplicationListForReimbursement", userId);
	}

	@Override
	public String getMaxCode() {
		Object obj = getSqlMapClientTemplate().queryForObject("s_expense_application.getMaxCode");
		if (obj != null) {
		    return (String) obj;
		}
		return null;
	}
}