package com.sales.dao.impl;

import com.sales.dao.SInternalAnnouncementDAO;
import com.sales.model.SInternalAnnouncement;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SInternalAnnouncementDAOImpl extends SqlMapClientDaoSupport implements SInternalAnnouncementDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_internal_announcement
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public SInternalAnnouncementDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_internal_announcement
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void insert(SInternalAnnouncement record) {
        getSqlMapClientTemplate().insert("s_internal_announcement.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_internal_announcement
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int updateByPrimaryKey(SInternalAnnouncement record) {
        int rows = getSqlMapClientTemplate().update("s_internal_announcement.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_internal_announcement
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int updateByPrimaryKeySelective(SInternalAnnouncement record) {
        int rows = getSqlMapClientTemplate().update("s_internal_announcement.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_internal_announcement
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public SInternalAnnouncement selectByPrimaryKey(Integer announcementId) {
        SInternalAnnouncement key = new SInternalAnnouncement();
        key.setAnnouncementId(announcementId);
        SInternalAnnouncement record = (SInternalAnnouncement) getSqlMapClientTemplate().queryForObject("s_internal_announcement.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_internal_announcement
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int deleteByPrimaryKey(Integer announcementId) {
        SInternalAnnouncement key = new SInternalAnnouncement();
        key.setAnnouncementId(announcementId);
        int rows = getSqlMapClientTemplate().delete("s_internal_announcement.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }
}