package com.sales.dao.impl;

import com.sales.dao.SMethodDAO;
import com.sales.model.SMethod;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SMethodDAOImpl extends SqlMapClientDaoSupport implements SMethodDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_method
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public SMethodDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_method
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void insert(SMethod record) {
        getSqlMapClientTemplate().insert("s_method.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_method
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int updateByPrimaryKey(SMethod record) {
        int rows = getSqlMapClientTemplate().update("s_method.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_method
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int updateByPrimaryKeySelective(SMethod record) {
        int rows = getSqlMapClientTemplate().update("s_method.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_method
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public SMethod selectByPrimaryKey(Integer methodId) {
        SMethod key = new SMethod();
        key.setMethodId(methodId);
        SMethod record = (SMethod) getSqlMapClientTemplate().queryForObject("s_method.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_method
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int deleteByPrimaryKey(Integer methodId) {
        SMethod key = new SMethod();
        key.setMethodId(methodId);
        int rows = getSqlMapClientTemplate().delete("s_method.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }
}