package com.sales.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.sales.dao.SParameterDAO;
import com.sales.model.SParameter;
import com.sales.service.SParameterService;

public class SParameterDAOImpl extends SqlMapClientDaoSupport implements SParameterDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_parameter
     *
     * @abatorgenerated Thu May 23 22:17:00 CST 2013
     */
    public SParameterDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_parameter
     *
     * @abatorgenerated Thu May 23 22:17:00 CST 2013
     */
    public void insert(SParameter record) {
        getSqlMapClientTemplate().insert("s_parameter.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_parameter
     *
     * @abatorgenerated Thu May 23 22:17:00 CST 2013
     */
    public int updateByPrimaryKey(SParameter record) {
        int rows = getSqlMapClientTemplate().update("s_parameter.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_parameter
     *
     * @abatorgenerated Thu May 23 22:17:00 CST 2013
     */
    public int updateByPrimaryKeySelective(SParameter record) {
        int rows = getSqlMapClientTemplate().update("s_parameter.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_parameter
     *
     * @abatorgenerated Thu May 23 22:17:00 CST 2013
     */
    public SParameter selectByPrimaryKey(Integer parameterId) {
        SParameter key = new SParameter();
        key.setParameterId(parameterId);
        SParameter record = (SParameter) getSqlMapClientTemplate().queryForObject("s_parameter.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_parameter
     *
     * @abatorgenerated Thu May 23 22:17:00 CST 2013
     */
    public int deleteByPrimaryKey(Integer parameterId) {
        SParameter key = new SParameter();
        key.setParameterId(parameterId);
        int rows = getSqlMapClientTemplate().delete("s_parameter.deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public List<SParameter> getParameterListPage(SParameter param) {
		return getSqlMapClientTemplate().queryForList("s_parameter.getParameterListPage", param);
	}

	@Override
	public Integer getParameterListPageCount(SParameter param) {
		return (Integer) getSqlMapClientTemplate().queryForObject("s_parameter.getParameterListPageCount", param);
	}

	@Override
	public SParameter selectByName(String parameterName) {
		SParameter key = new SParameter();
		key.setName(parameterName);
		SParameter record = (SParameter) getSqlMapClientTemplate().queryForObject("s_parameter.selectByName", key);
        return record;
	}
	
	
}