package com.sales.dao.impl;

import java.util.List;

import com.sales.dao.SPerformancePlanDAO;
import com.sales.model.SPerformancePlan;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SPerformancePlanDAOImpl extends SqlMapClientDaoSupport implements SPerformancePlanDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public SPerformancePlanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int insert(SPerformancePlan record) {
       return (Integer)getSqlMapClientTemplate().insert("s_performance_plan.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int updateByPrimaryKey(SPerformancePlan record) {
        int rows = getSqlMapClientTemplate().update("s_performance_plan.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int updateByPrimaryKeySelective(SPerformancePlan record) {
        int rows = getSqlMapClientTemplate().update("s_performance_plan.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public SPerformancePlan selectByPrimaryKey(Integer planId) {
        SPerformancePlan key = new SPerformancePlan();
        key.setPlanId(planId);
        SPerformancePlan record = (SPerformancePlan) getSqlMapClientTemplate().queryForObject("s_performance_plan.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int deleteByPrimaryKey(Integer planId) {
        SPerformancePlan key = new SPerformancePlan();
        key.setPlanId(planId);
        int rows = getSqlMapClientTemplate().delete("s_performance_plan.deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public List<SPerformancePlan> getPlanListPage(SPerformancePlan spp) {
		return getSqlMapClientTemplate().queryForList("s_performance_plan.getPlanListPage", spp);
	}

	@Override
	public Integer getPlanListPageCount(SPerformancePlan spp) {
		return (Integer) getSqlMapClientTemplate().queryForObject("s_performance_plan.getPlanListPageCount", spp);
	}
}