package com.sales.dao.impl;

import java.util.List;

import com.sales.dao.SPerformanceItemDAO;
import com.sales.model.SPerformanceItem;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SPerformanceItemDAOImpl extends SqlMapClientDaoSupport implements SPerformanceItemDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public SPerformanceItemDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void insert(SPerformanceItem record) {
        getSqlMapClientTemplate().insert("s_performance_item.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int updateByPrimaryKey(SPerformanceItem record) {
        int rows = getSqlMapClientTemplate().update("s_performance_item.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int updateByPrimaryKeySelective(SPerformanceItem record) {
        int rows = getSqlMapClientTemplate().update("s_performance_item.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public SPerformanceItem selectByPrimaryKey(Integer itemId) {
        SPerformanceItem key = new SPerformanceItem();
        key.setItemId(itemId);
        SPerformanceItem record = (SPerformanceItem) getSqlMapClientTemplate().queryForObject("s_performance_item.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int deleteByPrimaryKey(Integer itemId) {
        SPerformanceItem key = new SPerformanceItem();
        key.setItemId(itemId);
        int rows = getSqlMapClientTemplate().delete("s_performance_item.deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public List<SPerformanceItem> getItemListPage(SPerformanceItem spi) {
		return getSqlMapClientTemplate().queryForList("s_performance_item.getItemListPage", spi);
	}

	@Override
	public Integer getItemListPageCount(SPerformanceItem spi) {
		return (Integer) getSqlMapClientTemplate().queryForObject("s_performance_item.getItemListPageCount", spi);
	}

	@Override
	public List<SPerformanceItem> getPlanItemList(Integer planId) {
		return getSqlMapClientTemplate().queryForList("s_performance_item.getPlanItemList", planId);
	}
}