package com.sales.dao.impl;

import java.util.List;

import com.sales.dao.SPlanItemDAO;
import com.sales.model.SPlanItem;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SPlanItemDAOImpl extends SqlMapClientDaoSupport implements SPlanItemDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_plan_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public SPlanItemDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_plan_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void insert(SPlanItem record) {
        getSqlMapClientTemplate().insert("s_plan_item.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_plan_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int updateByPrimaryKey(SPlanItem record) {
        int rows = getSqlMapClientTemplate().update("s_plan_item.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_plan_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int updateByPrimaryKeySelective(SPlanItem record) {
        int rows = getSqlMapClientTemplate().update("s_plan_item.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_plan_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public SPlanItem selectByPrimaryKey(Integer planItemId) {
        SPlanItem key = new SPlanItem();
        key.setPlanItemId(planItemId);
        SPlanItem record = (SPlanItem) getSqlMapClientTemplate().queryForObject("s_plan_item.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_plan_item
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int deleteByPrimaryKey(Integer planItemId) {
        SPlanItem key = new SPlanItem();
        key.setPlanItemId(planItemId);
        int rows = getSqlMapClientTemplate().delete("s_plan_item.deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public List<SPlanItem> getPlanItemListByConditions(SPlanItem spi) {
		return getSqlMapClientTemplate().queryForList("s_plan_item.getPlanItemListByConditions", spi);
	}

	@Override
	public void deleteByPlanId(Integer planId) {
		SPlanItem key = new SPlanItem();
        key.setPlanId(planId);
        int rows = getSqlMapClientTemplate().delete("s_plan_item.deleteByPlanId", key);
	}
}