package com.sales.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.sales.dao.SPositionDAO;
import com.sales.model.SPosition;

public class SPositionDAOImpl extends SqlMapClientDaoSupport implements SPositionDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_position
     *
     * @abatorgenerated Mon Jun 03 22:16:57 CST 2013
     */
    public SPositionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_position
     *
     * @abatorgenerated Mon Jun 03 22:16:57 CST 2013
     */
    public void insert(SPosition record) {
        getSqlMapClientTemplate().insert("s_position.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_position
     *
     * @abatorgenerated Mon Jun 03 22:16:57 CST 2013
     */
    public int updateByPrimaryKey(SPosition record) {
        int rows = getSqlMapClientTemplate().update("s_position.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_position
     *
     * @abatorgenerated Mon Jun 03 22:16:57 CST 2013
     */
    public int updateByPrimaryKeySelective(SPosition record) {
        int rows = getSqlMapClientTemplate().update("s_position.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_position
     *
     * @abatorgenerated Mon Jun 03 22:16:57 CST 2013
     */
    public SPosition selectByPrimaryKey(Integer positionId) {
        SPosition key = new SPosition();
        key.setPositionId(positionId);
        SPosition record = (SPosition) getSqlMapClientTemplate().queryForObject("s_position.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_position
     *
     * @abatorgenerated Mon Jun 03 22:16:57 CST 2013
     */
    public int deleteByPrimaryKey(Integer positionId) {
        SPosition key = new SPosition();
        key.setPositionId(positionId);
        int rows = getSqlMapClientTemplate().delete("s_position.deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public List<SPosition> getPositionListByType(Integer type) {
		SPosition key = new SPosition();
        key.setType(type);
		return getSqlMapClientTemplate().queryForList("s_position.getPositionListByType", key);
	}
}