package com.sales.dao.impl;

import java.util.List;

import com.sales.dao.SRoleActionDAO;
import com.sales.model.SRoleAction;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SRoleActionDAOImpl extends SqlMapClientDaoSupport implements SRoleActionDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role_action
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public SRoleActionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role_action
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void insert(SRoleAction record) {
        getSqlMapClientTemplate().insert("s_role_action.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role_action
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int updateByPrimaryKey(SRoleAction record) {
        int rows = getSqlMapClientTemplate().update("s_role_action.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role_action
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int updateByPrimaryKeySelective(SRoleAction record) {
        int rows = getSqlMapClientTemplate().update("s_role_action.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role_action
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public SRoleAction selectByPrimaryKey(Integer roleActionId) {
        SRoleAction key = new SRoleAction();
        key.setRoleActionId(roleActionId);
        SRoleAction record = (SRoleAction) getSqlMapClientTemplate().queryForObject("s_role_action.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role_action
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int deleteByPrimaryKey(Integer roleActionId) {
        SRoleAction key = new SRoleAction();
        key.setRoleActionId(roleActionId);
        int rows = getSqlMapClientTemplate().delete("s_role_action.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public List<SRoleAction> getRoleActionListByRoleId(Integer roleId) {
		// TODO Auto-generated method stub
		List rActionList = getSqlMapClientTemplate().queryForList("s_role_action.getRoleActionListByRoleId", roleId);
		return rActionList;
	}

	@Override
	public void deleteByRoleId(Integer roleId) {
		// TODO Auto-generated method stub
		getSqlMapClientTemplate().delete("s_role_action.deleteByRoleId", roleId);
	}
}