package com.sales.dao.impl;

import java.util.List;

import com.sales.dao.SRoleDAO;
import com.sales.model.SRole;
import com.sales.model.SUser;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SRoleDAOImpl extends SqlMapClientDaoSupport implements SRoleDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public SRoleDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void insert(SRole record) {
        getSqlMapClientTemplate().insert("s_role.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int updateByPrimaryKey(SRole record) {
        int rows = getSqlMapClientTemplate().update("s_role.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int updateByPrimaryKeySelective(SRole record) {
        int rows = getSqlMapClientTemplate().update("s_role.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public SRole selectByPrimaryKey(Integer roleId) {
        SRole key = new SRole();
        key.setRoleId(roleId);
        SRole record = (SRole) getSqlMapClientTemplate().queryForObject("s_role.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_role
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int deleteByPrimaryKey(Integer roleId) {
        SRole key = new SRole();
        key.setRoleId(roleId);
        int rows = getSqlMapClientTemplate().delete("s_role.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public List<SRole> getRoleList() {
		// TODO Auto-generated method stub
		List roleList = getSqlMapClientTemplate().queryForList("s_role.getRoleList");
		return roleList;
	}

	@Override
	public List<SUser> getUsers(Integer positionId) {
		List userList = getSqlMapClientTemplate().queryForList("s_user.getUserListByRole", positionId);
		return userList;
	}
	
	
}