package com.sales.dao.impl;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.sales.dao.SSalesQuotationDAO;
import com.sales.model.SSalesQuotation;

public class SSalesQuotationDAOImpl extends SqlMapClientDaoSupport implements SSalesQuotationDAO {
 
    public SSalesQuotationDAOImpl() {
        super();
    }
 
    public Integer insertQuotation(SSalesQuotation quotation) {
    	return (Integer) getSqlMapClientTemplate().insert("s_sales_quotation.insertQuotation", quotation);
    }

    public void updateQuotation(SSalesQuotation quotation) {
        getSqlMapClientTemplate().update("s_sales_quotation.updateQuotation", quotation); 
    }
 
    public SSalesQuotation getQuotationById(Map queryMap) { 
        SSalesQuotation quotation = (SSalesQuotation) getSqlMapClientTemplate().queryForObject("s_sales_quotation.getQuotationById", queryMap);
        return quotation;
    }
 
    public SSalesQuotation getQuotationById(Integer quotationId) { 
        SSalesQuotation quotation = (SSalesQuotation) getSqlMapClientTemplate().queryForObject("s_sales_quotation.getQuotationByIdNoFilter", quotationId);
        return quotation;
    }
    
    public List getQuotationList(Map queryMap){
    	List quotationList = getSqlMapClientTemplate().queryForList("s_sales_quotation.getQuotationList", queryMap);
    	return quotationList;
    }
    
    public Integer getQuotationCount(Map queryMap){
    	Integer quotationCount = (Integer) getSqlMapClientTemplate().queryForObject("s_sales_quotation.getQuotationCount", queryMap);
    	return quotationCount;
    }
    

	/**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_sales_quotation
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int deleteByPrimaryKey(Integer quotationId) {
        SSalesQuotation key = new SSalesQuotation();
        key.setQuotationId(quotationId);
        int rows = getSqlMapClientTemplate().delete("s_sales_quotation.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }
 
    public String getMaxCode(){
    	Object obj = getSqlMapClientTemplate().queryForObject("s_sales_quotation.getMaxCode");
		if (obj != null) {
		    return (String) obj;
		}
		return null;
    }
      
	@Override
	public List getAllQuotationList(Map queryMap) {
		// TODO Auto-generated method stub
		List quotationList = getSqlMapClientTemplate().queryForList("s_sales_quotation.getAllQuotationList", queryMap);
    	return quotationList;
	} 

}