package com.sales.dao.impl;

import java.util.List;

import com.sales.dao.STripApplicationDAO;
import com.sales.model.STripApplication;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class STripApplicationDAOImpl extends SqlMapClientDaoSupport implements STripApplicationDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_application
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public STripApplicationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_application
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer insert(STripApplication record) {
        return (Integer) getSqlMapClientTemplate().insert("s_trip_application.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_application
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int updateByPrimaryKey(STripApplication record) {
        int rows = getSqlMapClientTemplate().update("s_trip_application.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_application
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int updateByPrimaryKeySelective(STripApplication record) {
        int rows = getSqlMapClientTemplate().update("s_trip_application.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_application
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public STripApplication selectByPrimaryKey(Integer tripId) {
        STripApplication key = new STripApplication();
        key.setTripId(tripId);
        STripApplication record = (STripApplication) getSqlMapClientTemplate().queryForObject("s_trip_application.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_application
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int deleteByPrimaryKey(Integer tripId) {
        STripApplication key = new STripApplication();
        key.setTripId(tripId);
        int rows = getSqlMapClientTemplate().delete("s_trip_application.deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public List<STripApplication> getTripApplicationListPage(STripApplication ta) {
		return getSqlMapClientTemplate().queryForList("s_trip_application.getTripApplicationListPage", ta);
	}

	@Override
	public Integer getTripApplicationListPageCount(STripApplication ta) {
		return (Integer) getSqlMapClientTemplate().queryForObject("s_trip_application.getTripApplicationListPageCount", ta);
	}

	@Override
	public List<STripApplication> getTripApplicationListForReimbursement(Integer userId) {
		return getSqlMapClientTemplate().queryForList("s_trip_application.getTripApplicationListForReimbursement", userId);
	}

	@Override
	public String getMaxCode() {
		Object obj = getSqlMapClientTemplate().queryForObject("s_trip_application.getMaxCode");
		if (obj != null) {
		    return (String) obj;
		}
		return null;
	}
}