package com.sales.dao.impl;

import com.sales.dao.STripExpenseDAO;
import com.sales.model.STripExpense;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class STripExpenseDAOImpl extends SqlMapClientDaoSupport implements STripExpenseDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_expense
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public STripExpenseDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_expense
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void insert(STripExpense record) {
        getSqlMapClientTemplate().insert("s_trip_expense.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_expense
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int updateByPrimaryKey(STripExpense record) {
        int rows = getSqlMapClientTemplate().update("s_trip_expense.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_expense
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int updateByPrimaryKeySelective(STripExpense record) {
        int rows = getSqlMapClientTemplate().update("s_trip_expense.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_expense
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public STripExpense selectByPrimaryKey(Integer tripExpenseId) {
        STripExpense key = new STripExpense();
        key.setTripExpenseId(tripExpenseId);
        STripExpense record = (STripExpense) getSqlMapClientTemplate().queryForObject("s_trip_expense.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_trip_expense
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int deleteByPrimaryKey(Integer tripExpenseId) {
        STripExpense key = new STripExpense();
        key.setTripExpenseId(tripExpenseId);
        int rows = getSqlMapClientTemplate().delete("s_trip_expense.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }
}