package com.sales.dao.impl;

import java.util.List;

import com.sales.dao.SUserPerformancePlanDAO;
import com.sales.model.SUserPerformancePlan;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SUserPerformancePlanDAOImpl extends SqlMapClientDaoSupport implements SUserPerformancePlanDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public SUserPerformancePlanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer insert(SUserPerformancePlan record) {
        return  (Integer) getSqlMapClientTemplate().insert("s_user_performance_plan.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int updateByPrimaryKey(SUserPerformancePlan record) {
        int rows = getSqlMapClientTemplate().update("s_user_performance_plan.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int updateByPrimaryKeySelective(SUserPerformancePlan record) {
        int rows = getSqlMapClientTemplate().update("s_user_performance_plan.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public SUserPerformancePlan selectByPrimaryKey(Integer performancePlanId) {
        SUserPerformancePlan key = new SUserPerformancePlan();
        key.setPerformancePlanId(performancePlanId);
        SUserPerformancePlan record = (SUserPerformancePlan) getSqlMapClientTemplate().queryForObject("s_user_performance_plan.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_plan
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int deleteByPrimaryKey(Integer performancePlanId) {
        SUserPerformancePlan key = new SUserPerformancePlan();
        key.setPerformancePlanId(performancePlanId);
        int rows = getSqlMapClientTemplate().delete("s_user_performance_plan.deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public List<SUserPerformancePlan> getUserPlanListPage(SUserPerformancePlan upp) {
		return getSqlMapClientTemplate().queryForList("s_user_performance_plan.getUserPlanListPage", upp);
	}

	@Override
	public Integer getUserPlanListPageCount(SUserPerformancePlan upp) {
		return (Integer) getSqlMapClientTemplate().queryForObject("s_user_performance_plan.getUserPlanListPageCount", upp);
	}
}