package com.sales.dao.impl;

import java.util.List;

import com.sales.dao.SUserPerformanceItemDAO;
import com.sales.model.SUserPerformanceItem;
import com.sales.model.SUserPerformancePlan;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SUserPerformanceItemDAOImpl extends SqlMapClientDaoSupport implements SUserPerformanceItemDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public SUserPerformanceItemDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void insert(SUserPerformanceItem record) {
        getSqlMapClientTemplate().insert("s_user_performance_item.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int updateByPrimaryKey(SUserPerformanceItem record) {
        int rows = getSqlMapClientTemplate().update("s_user_performance_item.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int updateByPrimaryKeySelective(SUserPerformanceItem record) {
        int rows = getSqlMapClientTemplate().update("s_user_performance_item.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public SUserPerformanceItem selectByPrimaryKey(Integer performanceItemId) {
        SUserPerformanceItem key = new SUserPerformanceItem();
        key.setPerformanceItemId(performanceItemId);
        SUserPerformanceItem record = (SUserPerformanceItem) getSqlMapClientTemplate().queryForObject("s_user_performance_item.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table s_user_performance_item
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public int deleteByPrimaryKey(Integer performanceItemId) {
        SUserPerformanceItem key = new SUserPerformanceItem();
        key.setPerformanceItemId(performanceItemId);
        int rows = getSqlMapClientTemplate().delete("s_user_performance_item.deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public void deleteByUserPlanId(Integer userPlanId) {
		SUserPerformanceItem key = new SUserPerformanceItem();
        key.setPerformancePlanId(userPlanId);
		getSqlMapClientTemplate().delete("s_user_performance_item.deleteByUserPlanId", key);
	}

	@Override
	public List<SUserPerformanceItem> getUserItemListPage(SUserPerformanceItem upi) {
		return getSqlMapClientTemplate().queryForList("s_user_performance_item.getUserItemListPage", upi);
	}

	@Override
	public Integer getUserItemListPageCount(SUserPerformanceItem upi) {
		return (Integer) getSqlMapClientTemplate().queryForObject("s_user_performance_item.getUserItemListPageCount", upi);
	}
}