package com.sales.model;

import java.util.Date;

import com.sales.common.DisplayAnnotation;

public class SCarRepairReimbursement extends Page {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_reimbursement.car_reimbursement_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer carReimbursementId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_reimbursement.car_reimbursement_code
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String carReimbursementCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_reimbursement.reimbursement_time
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    @DisplayAnnotation(name="报销日期")
    private Date reimbursementTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_reimbursement.reimbursement_comment
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    @DisplayAnnotation(name="报销备注")
    private String reimbursementComment;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_reimbursement.reimbursement_sum
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    @DisplayAnnotation(name="报销金额")
    private Float reimbursementSum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_reimbursement.uppercase
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String uppercase;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_reimbursement.repair_factory_phone
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    @DisplayAnnotation(name="维修厂联系电话")
    private String repairFactoryPhone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_reimbursement.car_application_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer carApplicationId;
    
    private Integer userId;
    
    private Integer status;
    @DisplayAnnotation(name="车牌号")
    private String plateNumber;
    @DisplayAnnotation(name="申请人")
    private String userName;
    
    private SCarRepairApplication ca;

    

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_reimbursement.car_reimbursement_id
     *
     * @return the value of s_car_repair_reimbursement.car_reimbursement_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getCarReimbursementId() {
        return carReimbursementId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_reimbursement.car_reimbursement_id
     *
     * @param carReimbursementId the value for s_car_repair_reimbursement.car_reimbursement_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setCarReimbursementId(Integer carReimbursementId) {
        this.carReimbursementId = carReimbursementId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_reimbursement.car_reimbursement_code
     *
     * @return the value of s_car_repair_reimbursement.car_reimbursement_code
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getCarReimbursementCode() {
        return carReimbursementCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_reimbursement.car_reimbursement_code
     *
     * @param carReimbursementCode the value for s_car_repair_reimbursement.car_reimbursement_code
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setCarReimbursementCode(String carReimbursementCode) {
        this.carReimbursementCode = carReimbursementCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_reimbursement.reimbursement_time
     *
     * @return the value of s_car_repair_reimbursement.reimbursement_time
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Date getReimbursementTime() {
        return reimbursementTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_reimbursement.reimbursement_time
     *
     * @param reimbursementTime the value for s_car_repair_reimbursement.reimbursement_time
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setReimbursementTime(Date reimbursementTime) {
        this.reimbursementTime = reimbursementTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_reimbursement.reimbursement_comment
     *
     * @return the value of s_car_repair_reimbursement.reimbursement_comment
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getReimbursementComment() {
        return reimbursementComment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_reimbursement.reimbursement_comment
     *
     * @param reimbursementComment the value for s_car_repair_reimbursement.reimbursement_comment
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setReimbursementComment(String reimbursementComment) {
        this.reimbursementComment = reimbursementComment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_reimbursement.reimbursement_sum
     *
     * @return the value of s_car_repair_reimbursement.reimbursement_sum
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Float getReimbursementSum() {
        return reimbursementSum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_reimbursement.reimbursement_sum
     *
     * @param reimbursementSum the value for s_car_repair_reimbursement.reimbursement_sum
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setReimbursementSum(Float reimbursementSum) {
        this.reimbursementSum = reimbursementSum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_reimbursement.uppercase
     *
     * @return the value of s_car_repair_reimbursement.uppercase
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getUppercase() {
        return uppercase;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_reimbursement.uppercase
     *
     * @param uppercase the value for s_car_repair_reimbursement.uppercase
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setUppercase(String uppercase) {
        this.uppercase = uppercase;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_reimbursement.repair_factory_phone
     *
     * @return the value of s_car_repair_reimbursement.repair_factory_phone
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getRepairFactoryPhone() {
        return repairFactoryPhone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_reimbursement.repair_factory_phone
     *
     * @param repairFactoryPhone the value for s_car_repair_reimbursement.repair_factory_phone
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setRepairFactoryPhone(String repairFactoryPhone) {
        this.repairFactoryPhone = repairFactoryPhone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_reimbursement.car_application_id
     *
     * @return the value of s_car_repair_reimbursement.car_application_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getCarApplicationId() {
        return carApplicationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_reimbursement.car_application_id
     *
     * @param carApplicationId the value for s_car_repair_reimbursement.car_application_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setCarApplicationId(Integer carApplicationId) {
        this.carApplicationId = carApplicationId;
    }

	/**
	 * @return the userId
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * @return the status
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * @return the plateNumber
	 */
	public String getPlateNumber() {
		return plateNumber;
	}

	/**
	 * @param plateNumber the plateNumber to set
	 */
	public void setPlateNumber(String plateNumber) {
		this.plateNumber = plateNumber;
	}

	/**
	 * @return the userName
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * @param userName the userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * @return the ca
	 */
	public SCarRepairApplication getCa() {
		return ca;
	}

	/**
	 * @param ca the ca to set
	 */
	public void setCa(SCarRepairApplication ca) {
		this.ca = ca;
	}

 
}