package com.sales.model;

import java.util.Date;

import com.sales.common.DisplayAnnotation;

public class SCarRepairApplication extends Page {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_application.car_application_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer carApplicationId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_application.car_application_code
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String carApplicationCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_application.user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_application.application_time
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    @DisplayAnnotation(name="申请日期")
    private Date applicationTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_application.repair_comment
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    @DisplayAnnotation(name="备注")
    private String repairComment;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_application.status
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_application.repair_time
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    @DisplayAnnotation(name="修理日期")
    private Date repairTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_application.repair_sum
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    @DisplayAnnotation(name="预计金额")
    private Float repairSum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_application.uppercase
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String uppercase;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_application.plate_number
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    @DisplayAnnotation(name="车牌号")
    private String plateNumber;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_car_repair_application.is_insurance
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer isInsurance;
    
    @DisplayAnnotation(name="申请人")
    private String userName;
    @DisplayAnnotation(name="是否保险")
    private String isInsuranceName;

    /**
	 * @return the isInsuranceName
	 */
	public String getIsInsuranceName() {
		if (this.isInsurance == null ) {
			return "";
		} else if (this.isInsurance.intValue() == 0) {
			return "否";
		} else {
			return "是";
		}
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_application.car_application_id
     *
     * @return the value of s_car_repair_application.car_application_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getCarApplicationId() {
        return carApplicationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_application.car_application_id
     *
     * @param carApplicationId the value for s_car_repair_application.car_application_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setCarApplicationId(Integer carApplicationId) {
        this.carApplicationId = carApplicationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_application.car_application_code
     *
     * @return the value of s_car_repair_application.car_application_code
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getCarApplicationCode() {
        return carApplicationCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_application.car_application_code
     *
     * @param carApplicationCode the value for s_car_repair_application.car_application_code
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setCarApplicationCode(String carApplicationCode) {
        this.carApplicationCode = carApplicationCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_application.user_id
     *
     * @return the value of s_car_repair_application.user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_application.user_id
     *
     * @param userId the value for s_car_repair_application.user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_application.application_time
     *
     * @return the value of s_car_repair_application.application_time
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Date getApplicationTime() {
        return applicationTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_application.application_time
     *
     * @param applicationTime the value for s_car_repair_application.application_time
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setApplicationTime(Date applicationTime) {
        this.applicationTime = applicationTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_application.repair_comment
     *
     * @return the value of s_car_repair_application.repair_comment
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getRepairComment() {
        return repairComment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_application.repair_comment
     *
     * @param repairComment the value for s_car_repair_application.repair_comment
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setRepairComment(String repairComment) {
        this.repairComment = repairComment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_application.status
     *
     * @return the value of s_car_repair_application.status
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_application.status
     *
     * @param status the value for s_car_repair_application.status
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_application.repair_time
     *
     * @return the value of s_car_repair_application.repair_time
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Date getRepairTime() {
        return repairTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_application.repair_time
     *
     * @param repairTime the value for s_car_repair_application.repair_time
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setRepairTime(Date repairTime) {
        this.repairTime = repairTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_application.repair_sum
     *
     * @return the value of s_car_repair_application.repair_sum
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Float getRepairSum() {
        return repairSum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_application.repair_sum
     *
     * @param repairSum the value for s_car_repair_application.repair_sum
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setRepairSum(Float repairSum) {
        this.repairSum = repairSum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_application.uppercase
     *
     * @return the value of s_car_repair_application.uppercase
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getUppercase() {
        return uppercase;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_application.uppercase
     *
     * @param uppercase the value for s_car_repair_application.uppercase
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setUppercase(String uppercase) {
        this.uppercase = uppercase;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_application.plate_number
     *
     * @return the value of s_car_repair_application.plate_number
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_application.plate_number
     *
     * @param plateNumber the value for s_car_repair_application.plate_number
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_car_repair_application.is_insurance
     *
     * @return the value of s_car_repair_application.is_insurance
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getIsInsurance() {
        return isInsurance;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_car_repair_application.is_insurance
     *
     * @param isInsurance the value for s_car_repair_application.is_insurance
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setIsInsurance(Integer isInsurance) {
        this.isInsurance = isInsurance;
    }

	/**
	 * @return the userName
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * @param userName the userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}
}