package com.sales.model;

import java.util.Date;

import com.sales.common.NormalFun;

public class SCustomerLinkman {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_linkman.linkman_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer linkmanId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_linkman.customer_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer customerId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_linkman.station_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String station;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_linkman.name
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_linkman.department_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String department;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_linkman.mobile
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String mobile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_linkman.phone
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String phone;
    
    private String fax;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_linkman.email
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String email;
    
    private Date birthday;			//����
    private String hobbies;			//����
    
    private Integer relationUs;
    private Integer createUserId;
    private String createUserName;
    private Integer customerOwnerUserId;
	private String customerOwnerUserName;
    private String isSelect;

	public String getIsSelect() {
		return isSelect;
	}

	public void setIsSelect(String isSelect) {
		this.isSelect = isSelect;
	}
	
    public Integer getCustomerOwnerUserId() {
		return customerOwnerUserId;
	}

	public void setCustomerOwnerUserId(Integer customerOwnerUserId) {
		this.customerOwnerUserId = customerOwnerUserId;
	}

	public String getCustomerOwnerUserName() {
		return customerOwnerUserName;
	}

	public void setCustomerOwnerUserName(String customerOwnerUserName) {
		this.customerOwnerUserName = customerOwnerUserName;
	}
    
    public Integer getCreateUserId() {
		return createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public String getCreateUserName() {
		return createUserName;
	}

	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	public Integer getRelationUs() {
		return relationUs;
	}

	public void setRelationUs(Integer relationUs) {
		this.relationUs = relationUs;
	}

	public Integer getRelationComp() {
		if(relationComp != null)
			return relationComp;
		else
			return 0;
	}

	public void setRelationComp(Integer relationComp) {
		this.relationComp = relationComp;
	}

	private Integer relationComp;
    private String relationUsName;
    private String relationCompName;
    private String customerName;

    public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getRelationUsName() {
		return relationUsName;
	}

	public void setRelationUsName(String relationUsName) {
		this.relationUsName = relationUsName;
	}

	public String getRelationCompName() {
		return relationCompName;
	}

	public void setRelationCompName(String relationCompName) {
		this.relationCompName = relationCompName;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_linkman.linkman_id
     *
     * @return the value of s_customer_linkman.linkman_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getLinkmanId() {
        return linkmanId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_linkman.linkman_id
     *
     * @param linkmanId the value for s_customer_linkman.linkman_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setLinkmanId(Integer linkmanId) {
        this.linkmanId = linkmanId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_linkman.customer_id
     *
     * @return the value of s_customer_linkman.customer_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_linkman.customer_id
     *
     * @param customerId the value for s_customer_linkman.customer_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }



    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_linkman.name
     *
     * @return the value of s_customer_linkman.name
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_linkman.name
     *
     * @param name the value for s_customer_linkman.name
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    public String getStation() {
		return station;
	}

	public void setStation(String station) {
		this.station = station;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_linkman.mobile
     *
     * @return the value of s_customer_linkman.mobile
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_linkman.mobile
     *
     * @param mobile the value for s_customer_linkman.mobile
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_linkman.phone
     *
     * @return the value of s_customer_linkman.phone
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_linkman.phone
     *
     * @param phone the value for s_customer_linkman.phone
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
	 * @return the fax
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * @param fax the fax to set
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_linkman.email
     *
     * @return the value of s_customer_linkman.email
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_linkman.email
     *
     * @param email the value for s_customer_linkman.email
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setEmail(String email) {
        this.email = email;
    }
	/**
	 * @return the birthday
	 */
	public Date getBirthday() {
		return birthday;
	}
	
	public String getBirthdayFormat() {
		
		return NormalFun.formatDateString(birthday);
	}

	/**
	 * @param birthday the birthday to set
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * ����
	 * @return the hobbies
	 */
	public String getHobbies() {
		return hobbies;
	}

	/**
	 * ����
	 * @param hobbies the hobbies to set
	 */
	public void setHobbies(String hobbies) {
		this.hobbies = hobbies;
	}
    
    
}