package com.sales.model;

public class SCustomerFinEvaluation {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_fin_evaluation.eva_id
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    private Integer evaId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_fin_evaluation.customer_id
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    private Integer customerId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_fin_evaluation.eva_salemanager
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    private Integer evaSalemanager;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_fin_evaluation.eva_salegen
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    private Integer evaSalegen;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_fin_evaluation.eva_finmanager
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    private Integer evaFinmanager;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_fin_evaluation.comment
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    private String comment;
    
    private String evaSalemanagerName;
    private String evaSalegenName;
    
    private Integer createUserId;
    private String createUserName;
    
    public Integer getCreateUserId() {
		return createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public String getCreateUserName() {
		return createUserName;
	}

	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	public String getEvaSalemanagerName() {
		return evaSalemanagerName;
	}

	public void setEvaSalemanagerName(String evaSalemanagerName) {
		this.evaSalemanagerName = evaSalemanagerName;
	}

	public String getEvaSalegenName() {
		return evaSalegenName;
	}

	public void setEvaSalegenName(String evaSalegenName) {
		this.evaSalegenName = evaSalegenName;
	}

	public String getEvaFinmanagerName() {
		return evaFinmanagerName;
	}

	public void setEvaFinmanagerName(String evaFinmanagerName) {
		this.evaFinmanagerName = evaFinmanagerName;
	}

	private String evaFinmanagerName;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_fin_evaluation.eva_id
     *
     * @return the value of s_customer_fin_evaluation.eva_id
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public Integer getEvaId() {
        return evaId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_fin_evaluation.eva_id
     *
     * @param evaId the value for s_customer_fin_evaluation.eva_id
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public void setEvaId(Integer evaId) {
        this.evaId = evaId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_fin_evaluation.customer_id
     *
     * @return the value of s_customer_fin_evaluation.customer_id
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_fin_evaluation.customer_id
     *
     * @param customerId the value for s_customer_fin_evaluation.customer_id
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_fin_evaluation.eva_salemanager
     *
     * @return the value of s_customer_fin_evaluation.eva_salemanager
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public Integer getEvaSalemanager() {
        return evaSalemanager;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_fin_evaluation.eva_salemanager
     *
     * @param evaSalemanager the value for s_customer_fin_evaluation.eva_salemanager
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public void setEvaSalemanager(Integer evaSalemanager) {
        this.evaSalemanager = evaSalemanager;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_fin_evaluation.eva_salegen
     *
     * @return the value of s_customer_fin_evaluation.eva_salegen
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public Integer getEvaSalegen() {
        return evaSalegen;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_fin_evaluation.eva_salegen
     *
     * @param evaSalegen the value for s_customer_fin_evaluation.eva_salegen
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public void setEvaSalegen(Integer evaSalegen) {
        this.evaSalegen = evaSalegen;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_fin_evaluation.eva_finmanager
     *
     * @return the value of s_customer_fin_evaluation.eva_finmanager
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public Integer getEvaFinmanager() {
        return evaFinmanager;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_fin_evaluation.eva_finmanager
     *
     * @param evaFinmanager the value for s_customer_fin_evaluation.eva_finmanager
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public void setEvaFinmanager(Integer evaFinmanager) {
        this.evaFinmanager = evaFinmanager;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_fin_evaluation.comment
     *
     * @return the value of s_customer_fin_evaluation.comment
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_fin_evaluation.comment
     *
     * @param comment the value for s_customer_fin_evaluation.comment
     *
     * @abatorgenerated Thu Jun 27 16:53:22 CST 2013
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}