package com.sales.model;

public class SCustomerLevel {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_level.customer_level_id
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    private Integer customerLevelId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_level.customer_id
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    private Integer customerId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_level.level_id
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    private Integer levelId;
    
    public Integer getCreateUserId() {
		return createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public String getCreateUserName() {
		return createUserName;
	}

	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	private String levelName;
    private Integer createUserId;
    private String createUserName;

    public String getLevelName() {
		return levelName;
	}

	public void setLevelName(String levelName) {
		this.levelName = levelName;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_level.customer_level_id
     *
     * @return the value of s_customer_level.customer_level_id
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    public Integer getCustomerLevelId() {
        return customerLevelId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_level.customer_level_id
     *
     * @param customerLevelId the value for s_customer_level.customer_level_id
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    public void setCustomerLevelId(Integer customerLevelId) {
        this.customerLevelId = customerLevelId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_level.customer_id
     *
     * @return the value of s_customer_level.customer_id
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_level.customer_id
     *
     * @param customerId the value for s_customer_level.customer_id
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_level.level_id
     *
     * @return the value of s_customer_level.level_id
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    public Integer getLevelId() {
    	if(levelId == null)
    		return -1;
        return levelId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_level.level_id
     *
     * @param levelId the value for s_customer_level.level_id
     *
     * @abatorgenerated Sat Jul 13 21:37:06 CST 2013
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }
}