package com.sales.model;

import java.util.Date;

public class SCustomerProject {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_project.project_id
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    private Integer projectId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_project.name
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_project.customer_id
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    private Integer customerId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_project.start_time
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    private Date startTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_project.plan_end_time
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    private Date planEndTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_project.amount
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    private Integer amount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_project.evaluation_saler
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    private Integer evaluationSaler;
    private String evaluationSalerName;
    private Integer createUserId;
    private String createUserName;
    private Integer LinkmanId;
    private String LinkmanName;

	public Integer getCreateUserId() {
		return createUserId;
	}

	public Integer getLinkmanId() {
		return LinkmanId;
	}

	public void setLinkmanId(Integer linkmanId) {
		LinkmanId = linkmanId;
	}

	public String getLinkmanName() {
		return LinkmanName;
	}

	public void setLinkmanName(String linkmanName) {
		LinkmanName = linkmanName;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public String getCreateUserName() {
		return createUserName;
	}

	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_project.evaluation_manager
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    private Integer evaluationManager;
    private String evaluationManagerName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_project.evaluation_gen
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    private Integer evaluationGen;
    private String evaluationGenName;

    public String getEvaluationSalerName() {
		return evaluationSalerName;
	}

	public void setEvaluationSalerName(String evaluationSalerName) {
		this.evaluationSalerName = evaluationSalerName;
	}

	public String getEvaluationManagerName() {
		return evaluationManagerName;
	}

	public void setEvaluationManagerName(String evaluationManagerName) {
		this.evaluationManagerName = evaluationManagerName;
	}

	public String getEvaluationGenName() {
		return evaluationGenName;
	}

	public void setEvaluationGenName(String evaluationGenName) {
		this.evaluationGenName = evaluationGenName;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_project.use_partion
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    private String usePartion;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_project.use_attention
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    private String useAttention;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_project.using_status
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    private String usingStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_project.problem
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    private String problem;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_project.solution
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    private String solution;
    
    private String customerName;

    public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_project.project_id
     *
     * @return the value of s_customer_project.project_id
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_project.project_id
     *
     * @param projectId the value for s_customer_project.project_id
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_project.name
     *
     * @return the value of s_customer_project.name
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_project.name
     *
     * @param name the value for s_customer_project.name
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_project.customer_id
     *
     * @return the value of s_customer_project.customer_id
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_project.customer_id
     *
     * @param customerId the value for s_customer_project.customer_id
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_project.start_time
     *
     * @return the value of s_customer_project.start_time
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_project.start_time
     *
     * @param startTime the value for s_customer_project.start_time
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_project.plan_end_time
     *
     * @return the value of s_customer_project.plan_end_time
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public Date getPlanEndTime() {
        return planEndTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_project.plan_end_time
     *
     * @param planEndTime the value for s_customer_project.plan_end_time
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public void setPlanEndTime(Date planEndTime) {
        this.planEndTime = planEndTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_project.amount
     *
     * @return the value of s_customer_project.amount
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_project.amount
     *
     * @param amount the value for s_customer_project.amount
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_project.evaluation_saler
     *
     * @return the value of s_customer_project.evaluation_saler
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public Integer getEvaluationSaler() {
        return evaluationSaler;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_project.evaluation_saler
     *
     * @param evaluationSaler the value for s_customer_project.evaluation_saler
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public void setEvaluationSaler(Integer evaluationSaler) {
        this.evaluationSaler = evaluationSaler;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_project.evaluation_manager
     *
     * @return the value of s_customer_project.evaluation_manager
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public Integer getEvaluationManager() {
        return evaluationManager;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_project.evaluation_manager
     *
     * @param evaluationManager the value for s_customer_project.evaluation_manager
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public void setEvaluationManager(Integer evaluationManager) {
        this.evaluationManager = evaluationManager;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_project.evaluation_gen
     *
     * @return the value of s_customer_project.evaluation_gen
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public Integer getEvaluationGen() {
        return evaluationGen;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_project.evaluation_gen
     *
     * @param evaluationGen the value for s_customer_project.evaluation_gen
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public void setEvaluationGen(Integer evaluationGen) {
        this.evaluationGen = evaluationGen;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_project.use_partion
     *
     * @return the value of s_customer_project.use_partion
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public String getUsePartion() {
        return usePartion;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_project.use_partion
     *
     * @param usePartion the value for s_customer_project.use_partion
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public void setUsePartion(String usePartion) {
        this.usePartion = usePartion;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_project.use_attention
     *
     * @return the value of s_customer_project.use_attention
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public String getUseAttention() {
        return useAttention;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_project.use_attention
     *
     * @param useAttention the value for s_customer_project.use_attention
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public void setUseAttention(String useAttention) {
        this.useAttention = useAttention;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_project.using_status
     *
     * @return the value of s_customer_project.using_status
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public String getUsingStatus() {
        return usingStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_project.using_status
     *
     * @param usingStatus the value for s_customer_project.using_status
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public void setUsingStatus(String usingStatus) {
        this.usingStatus = usingStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_project.problem
     *
     * @return the value of s_customer_project.problem
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_project.problem
     *
     * @param problem the value for s_customer_project.problem
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public void setProblem(String problem) {
        this.problem = problem;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_project.solution
     *
     * @return the value of s_customer_project.solution
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public String getSolution() {
        return solution;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_project.solution
     *
     * @param solution the value for s_customer_project.solution
     *
     * @abatorgenerated Thu Jun 27 16:47:57 CST 2013
     */
    public void setSolution(String solution) {
        this.solution = solution;
    }
}