package com.sales.model;

import java.util.Date;

public class SCustomerOwnerUser {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_owner_user.customer_owner_user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer customerOwnerUserId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_owner_user.customer_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer customerId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_customer_owner_user.user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer userId;
    
    private String customerName;

	private String userName;
	private Integer createUserId;
    private String createUserName;
	private Date addTime;
    private Date overTime;
    private Integer historyUserId;
    private Integer salegenId;
    private Integer finmanagerId;
    private String salegenName;
	private String finmanagerName;
	private String customerNumber;
	
    public String getCustomerNumber() {
		return customerNumber;
	}

	public void setCustomerNumber(String customerNumber) {
		this.customerNumber = customerNumber;
	}

	public Integer getSalegenId() {
		return salegenId;
	}

	public void setSalegenId(Integer salegenId) {
		this.salegenId = salegenId;
	}

	public Integer getFinmanagerId() {
		return finmanagerId;
	}

	public void setFinmanagerId(Integer finmanagerId) {
		this.finmanagerId = finmanagerId;
	}

	public String getSalegenName() {
		return salegenName;
	}

	public void setSalegenName(String salegenName) {
		this.salegenName = salegenName;
	}

	public String getFinmanagerName() {
		return finmanagerName;
	}

	public void setFinmanagerName(String finmanagerName) {
		this.finmanagerName = finmanagerName;
	}
    
    public Integer getHistoryUserId() {
		return historyUserId;
	}

	public void setHistoryUserId(Integer historyUserId) {
		this.historyUserId = historyUserId;
	}

	public Date getAddTime() {
		return addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	public Date getOverTime() {
		return overTime;
	}

	public void setOverTime(Date overTime) {
		this.overTime = overTime;
	}

    public Integer getCreateUserId() {
		return createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public String getCreateUserName() {
		return createUserName;
	}

	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_owner_user.customer_owner_user_id
     *
     * @return the value of s_customer_owner_user.customer_owner_user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getCustomerOwnerUserId() {
        return customerOwnerUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_owner_user.customer_owner_user_id
     *
     * @param customerOwnerUserId the value for s_customer_owner_user.customer_owner_user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setCustomerOwnerUserId(Integer customerOwnerUserId) {
        this.customerOwnerUserId = customerOwnerUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_owner_user.customer_id
     *
     * @return the value of s_customer_owner_user.customer_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_owner_user.customer_id
     *
     * @param customerId the value for s_customer_owner_user.customer_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_customer_owner_user.user_id
     *
     * @return the value of s_customer_owner_user.user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_customer_owner_user.user_id
     *
     * @param userId the value for s_customer_owner_user.user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}