package com.sales.model;

import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;

public class SInformation {
	
	public static final Integer STATUS_NOREAD = 1;
	public static final Integer STATUS_READED = 0;
	
	public enum BuzType {
		UNKONWN,			//未知
		PLAN,				// (1)销售计划
		ACTIVITY,				// 销售活动
		PROCESS_ASS,			// 流程通知
		SALE_QUO,				// 销售询价
		SALE_ORF,				// (5)销售报价
		SALE_ORD,				// 销售订单
		SALE_REQ,				// (7)采购申请
		SALE_POO,				// 采购订单
		SALE_STI,				// (9)采购入库
		SALE_SST,				// 销售出库通知
		SALE_STO,				// 销售出库
		SALE_SLE,				// (12)销售发票
		SALE_RCB				// (13)销售收款
	}
	
	/**
	 * 单据实体id
	 */
	private Integer buzId;
	
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_information.information_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer informationId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_information.title
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String title;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_information.image_url
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String imageUrl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_information.content
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String content;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_information.user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_information.resource
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String resource;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_information.add_time
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Timestamp addTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_information.status
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private int status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_information.type
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer type;
    private String typeName;
    private String userName;
    private String sendUserName;
    private String timeShow;
    private String contentCut;
    
    public String getTimeShow() {
    	if(addTime!=null){
    		SimpleDateFormat formatter=new SimpleDateFormat("yyyy-MM-dd HH:mm");
    		timeShow=formatter.format(addTime);
    	}
		return timeShow;
	}

	public void setTimeShow(String timeShow) {
		this.timeShow = timeShow;
	}

	public String getContentCut() {
		if(content!=null && !"".equals(content)){
			if(content.length()>8){
				contentCut = content.substring(0, 7)+"......";
			}else{
				contentCut = content;
			}
		}
		return contentCut;
	}

	public void setContentCut(String contentCut) {
		this.contentCut = contentCut;
	}

	public String getTypeName() {
    	if(type == 1){
    		typeName = "系统消息";
    	}else if(type == 2){
    		typeName = "用户消息";
    	}
		return typeName;
	}

	public String getUserName() {
		if(userId==null){
			userName = "后台系统";
		}
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getSendUserName() {
		return sendUserName;
	}

	public void setSendUserName(String sendUserName) {
		this.sendUserName = sendUserName;
	}

	public void setType(int type) {
		this.type = type;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Integer getSendUserId() {
		return sendUserId;
	}

	public void setSendUserId(Integer sendUserId) {
		this.sendUserId = sendUserId;
	}

	private String statusName;
    
    private Integer sendUserId;

    public String getStatusName() {
    	
    	if(status == STATUS_NOREAD){
    		statusName = "新消息";
    	}else{
    		statusName = "已读";
    	}
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_information.information_id
     *
     * @return the value of s_information.information_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getInformationId() {
        return informationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_information.information_id
     *
     * @param informationId the value for s_information.information_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setInformationId(Integer informationId) {
        this.informationId = informationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_information.title
     *
     * @return the value of s_information.title
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_information.title
     *
     * @param title the value for s_information.title
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_information.image_url
     *
     * @return the value of s_information.image_url
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_information.image_url
     *
     * @param imageUrl the value for s_information.image_url
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_information.content
     *
     * @return the value of s_information.content
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_information.content
     *
     * @param content the value for s_information.content
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_information.user_id
     *
     * @return the value of s_information.user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_information.user_id
     *
     * @param userId the value for s_information.user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_information.resource
     *
     * @return the value of s_information.resource
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_information.resource
     *
     * @param resource the value for s_information.resource
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setResource(String resource) {
        this.resource = resource;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_information.add_time
     *
     * @return the value of s_information.add_time
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Timestamp getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_information.add_time
     *
     * @param addTime the value for s_information.add_time
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setAddTime(Timestamp addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_information.status
     *
     * @return the value of s_information.status
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public int getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_information.status
     *
     * @param status the value for s_information.status
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setStatus(int status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_information.type
     *
     * @return the value of s_information.type
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_information.type
     *
     * @param type the value for s_information.type
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setType(Integer type) {
        this.type = type;
    }

	/**
	 * @return the buzId
	 */
	public Integer getBuzId() {
		return buzId;
	}

	/**
	 * @param buzId the buzId to set
	 */
	public void setBuzId(Integer buzId) {
		this.buzId = buzId;
	}
}