package com.sales.model;

import java.util.Date;

public class SInternalAnnouncement {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_internal_announcement.announcement_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer announcementId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_internal_announcement.topical
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String topical;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_internal_announcement.type_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer typeId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_internal_announcement.announce_user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer announceUserId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_internal_announcement.announce_time
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Date announceTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_internal_announcement.sendee_user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer sendeeUserId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_internal_announcement.comment
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String comment;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_internal_announcement.announcement_id
     *
     * @return the value of s_internal_announcement.announcement_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getAnnouncementId() {
        return announcementId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_internal_announcement.announcement_id
     *
     * @param announcementId the value for s_internal_announcement.announcement_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setAnnouncementId(Integer announcementId) {
        this.announcementId = announcementId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_internal_announcement.topical
     *
     * @return the value of s_internal_announcement.topical
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getTopical() {
        return topical;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_internal_announcement.topical
     *
     * @param topical the value for s_internal_announcement.topical
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setTopical(String topical) {
        this.topical = topical;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_internal_announcement.type_id
     *
     * @return the value of s_internal_announcement.type_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_internal_announcement.type_id
     *
     * @param typeId the value for s_internal_announcement.type_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_internal_announcement.announce_user_id
     *
     * @return the value of s_internal_announcement.announce_user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getAnnounceUserId() {
        return announceUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_internal_announcement.announce_user_id
     *
     * @param announceUserId the value for s_internal_announcement.announce_user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setAnnounceUserId(Integer announceUserId) {
        this.announceUserId = announceUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_internal_announcement.announce_time
     *
     * @return the value of s_internal_announcement.announce_time
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Date getAnnounceTime() {
        return announceTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_internal_announcement.announce_time
     *
     * @param announceTime the value for s_internal_announcement.announce_time
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setAnnounceTime(Date announceTime) {
        this.announceTime = announceTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_internal_announcement.sendee_user_id
     *
     * @return the value of s_internal_announcement.sendee_user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getSendeeUserId() {
        return sendeeUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_internal_announcement.sendee_user_id
     *
     * @param sendeeUserId the value for s_internal_announcement.sendee_user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setSendeeUserId(Integer sendeeUserId) {
        this.sendeeUserId = sendeeUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_internal_announcement.comment
     *
     * @return the value of s_internal_announcement.comment
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_internal_announcement.comment
     *
     * @param comment the value for s_internal_announcement.comment
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}