package com.sales.model;

public class SMethod {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_method.method_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer methodId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_method.action_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer actionId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_method.name
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_method.method
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String method;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_method.method_id
     *
     * @return the value of s_method.method_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getMethodId() {
        return methodId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_method.method_id
     *
     * @param methodId the value for s_method.method_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setMethodId(Integer methodId) {
        this.methodId = methodId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_method.action_id
     *
     * @return the value of s_method.action_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getActionId() {
        return actionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_method.action_id
     *
     * @param actionId the value for s_method.action_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_method.name
     *
     * @return the value of s_method.name
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_method.name
     *
     * @param name the value for s_method.name
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_method.method
     *
     * @return the value of s_method.method
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_method.method
     *
     * @param method the value for s_method.method
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setMethod(String method) {
        this.method = method;
    }
}