package com.sales.model;

import java.util.Date;

import com.sales.common.DisplayAnnotation;

public class SOvertime extends Page {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column s_overtime.overtime_id
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	private Integer overtimeId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column s_overtime.user_id
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	private Integer userId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column s_overtime.start_time
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	@DisplayAnnotation(name="加班日期")
	private Date startTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column s_overtime.hours
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	@DisplayAnnotation(name="加班小时")
	private Float hours;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column s_overtime.comment
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	@DisplayAnnotation(name="申请备注")
	private String comment;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column s_overtime.status
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	private Integer status;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column s_overtime.overtime_time
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	@DisplayAnnotation(name="申请日期")
	private Date overtimeTime;
	
	@DisplayAnnotation(name="申请人")
	private String userName;
	
	private String overtimeCode;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column s_overtime.overtime_id
	 * @return  the value of s_overtime.overtime_id
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	public Integer getOvertimeId() {
		return overtimeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column s_overtime.overtime_id
	 * @param overtimeId  the value for s_overtime.overtime_id
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	public void setOvertimeId(Integer overtimeId) {
		this.overtimeId = overtimeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column s_overtime.user_id
	 * @return  the value of s_overtime.user_id
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column s_overtime.user_id
	 * @param userId  the value for s_overtime.user_id
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column s_overtime.start_time
	 * @return  the value of s_overtime.start_time
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column s_overtime.start_time
	 * @param startTime  the value for s_overtime.start_time
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column s_overtime.hours
	 * @return  the value of s_overtime.hours
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	public Float getHours() {
		return hours;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column s_overtime.hours
	 * @param hours  the value for s_overtime.hours
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	public void setHours(Float hours) {
		this.hours = hours;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column s_overtime.comment
	 * @return  the value of s_overtime.comment
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column s_overtime.comment
	 * @param comment  the value for s_overtime.comment
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column s_overtime.status
	 * @return  the value of s_overtime.status
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column s_overtime.status
	 * @param status  the value for s_overtime.status
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column s_overtime.overtime_time
	 * @return  the value of s_overtime.overtime_time
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	public Date getOvertimeTime() {
		return overtimeTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column s_overtime.overtime_time
	 * @param overtimeTime  the value for s_overtime.overtime_time
	 * @abatorgenerated  Tue May 14 23:13:43 CST 2013
	 */
	public void setOvertimeTime(Date overtimeTime) {
		this.overtimeTime = overtimeTime;
	}

	/**
	 * @return the userName
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * @param userName the userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * @return the overtimeCode
	 */
	public String getOvertimeCode() {
		return overtimeCode;
	}

	/**
	 * @param overtimeCode the overtimeCode to set
	 */
	public void setOvertimeCode(String overtimeCode) {
		this.overtimeCode = overtimeCode;
	}
}