package com.sales.model;

public class SOvertimeCollection {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_overtime_collection.id
     *
     * @abatorgenerated Thu Jul 11 20:43:32 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_overtime_collection.user_id
     *
     * @abatorgenerated Thu Jul 11 20:43:32 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_overtime_collection.hours_collection
     *
     * @abatorgenerated Thu Jul 11 20:43:32 CST 2013
     */
    private Float hoursCollection;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_overtime_collection.id
     *
     * @return the value of s_overtime_collection.id
     *
     * @abatorgenerated Thu Jul 11 20:43:32 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_overtime_collection.id
     *
     * @param id the value for s_overtime_collection.id
     *
     * @abatorgenerated Thu Jul 11 20:43:32 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_overtime_collection.user_id
     *
     * @return the value of s_overtime_collection.user_id
     *
     * @abatorgenerated Thu Jul 11 20:43:32 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_overtime_collection.user_id
     *
     * @param userId the value for s_overtime_collection.user_id
     *
     * @abatorgenerated Thu Jul 11 20:43:32 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_overtime_collection.hours_collection
     *
     * @return the value of s_overtime_collection.hours_collection
     *
     * @abatorgenerated Thu Jul 11 20:43:32 CST 2013
     */
    public Float getHoursCollection() {
        return hoursCollection;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_overtime_collection.hours_collection
     *
     * @param hoursCollection the value for s_overtime_collection.hours_collection
     *
     * @abatorgenerated Thu Jul 11 20:43:32 CST 2013
     */
    public void setHoursCollection(Float hoursCollection) {
        this.hoursCollection = hoursCollection;
    }
}