package com.sales.model;

public class SParameter extends Page {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_parameter.parameter_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer parameterId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_parameter.name
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_parameter.value
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String value;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_parameter.comment
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private String comment;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_parameter.parameter_id
     *
     * @return the value of s_parameter.parameter_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getParameterId() {
        return parameterId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_parameter.parameter_id
     *
     * @param parameterId the value for s_parameter.parameter_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setParameterId(Integer parameterId) {
        this.parameterId = parameterId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_parameter.name
     *
     * @return the value of s_parameter.name
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_parameter.name
     *
     * @param name the value for s_parameter.name
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_parameter.value
     *
     * @return the value of s_parameter.value
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_parameter.value
     *
     * @param value the value for s_parameter.value
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_parameter.comment
     *
     * @return the value of s_parameter.comment
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_parameter.comment
     *
     * @param comment the value for s_parameter.comment
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}