package com.sales.model;

public class SPerformanceItem extends Page {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_performance_item.item_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private Integer itemId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_performance_item.sql_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private Integer sqlId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_performance_item.resource_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private Integer resourceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_performance_item.item_name
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private String itemName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_performance_item.assess_method
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private String assessMethod;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_performance_item.measurement_unit
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private String measurementUnit;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_performance_item.comment
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private String comment;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_performance_item.access_post_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private Integer accessPostId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_performance_item.post_type
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private Integer postType;
    
    private Integer specificWeight;
    
    private String resourceName;
    
    private String postTypeName;
    
    private String accessPostName;
    
    private String sqlName;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_performance_item.item_id
     *
     * @return the value of s_performance_item.item_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_performance_item.item_id
     *
     * @param itemId the value for s_performance_item.item_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_performance_item.sql_id
     *
     * @return the value of s_performance_item.sql_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public Integer getSqlId() {
        return sqlId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_performance_item.sql_id
     *
     * @param sqlId the value for s_performance_item.sql_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setSqlId(Integer sqlId) {
        this.sqlId = sqlId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_performance_item.resource_id
     *
     * @return the value of s_performance_item.resource_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_performance_item.resource_id
     *
     * @param resourceId the value for s_performance_item.resource_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_performance_item.item_name
     *
     * @return the value of s_performance_item.item_name
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_performance_item.item_name
     *
     * @param itemName the value for s_performance_item.item_name
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_performance_item.assess_method
     *
     * @return the value of s_performance_item.assess_method
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public String getAssessMethod() {
        return assessMethod;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_performance_item.assess_method
     *
     * @param assessMethod the value for s_performance_item.assess_method
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setAssessMethod(String assessMethod) {
        this.assessMethod = assessMethod;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_performance_item.measurement_unit
     *
     * @return the value of s_performance_item.measurement_unit
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public String getMeasurementUnit() {
        return measurementUnit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_performance_item.measurement_unit
     *
     * @param measurementUnit the value for s_performance_item.measurement_unit
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setMeasurementUnit(String measurementUnit) {
        this.measurementUnit = measurementUnit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_performance_item.comment
     *
     * @return the value of s_performance_item.comment
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_performance_item.comment
     *
     * @param comment the value for s_performance_item.comment
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_performance_item.access_post_id
     *
     * @return the value of s_performance_item.access_post_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public Integer getAccessPostId() {
        return accessPostId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_performance_item.access_post_id
     *
     * @param accessPostId the value for s_performance_item.access_post_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setAccessPostId(Integer accessPostId) {
        this.accessPostId = accessPostId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_performance_item.post_type
     *
     * @return the value of s_performance_item.post_type
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public Integer getPostType() {
        return postType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_performance_item.post_type
     *
     * @param postType the value for s_performance_item.post_type
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setPostType(Integer postType) {
        this.postType = postType;
    }

	/**
	 * @return the specificWeight
	 */
	public Integer getSpecificWeight() {
		return specificWeight;
	}

	/**
	 * @param specificWeight the specificWeight to set
	 */
	public void setSpecificWeight(Integer specificWeight) {
		this.specificWeight = specificWeight;
	}

	/**
	 * @return the resourceName
	 */
	public String getResourceName() {
		if (this.resourceId == null) {
			this.resourceName = "";
		}else if (this.resourceId.intValue() == 1) {
			this.resourceName = "非量化指标";
		}else if (this.resourceId.intValue() == 2) {
			this.resourceName = "量化指标";
		}else {
			this.resourceName = "";
		}
		return resourceName;
	}
	
	/**
	 * @return the postTypeName
	 */
	public String getPostTypeName() {
		if (this.postType == null) {
			this.postTypeName = "";
		}else if (this.postType.intValue() == 1) {
			this.postTypeName = "行政岗位";
		}else if (this.postType.intValue() == 2) {
			this.postTypeName = "业务岗位";
		}else {
			this.postTypeName = "";
		}
		return postTypeName;
	}

	/**
	 * @return the accessPostName
	 */
	public String getAccessPostName() {
		return accessPostName;
	}

	/**
	 * @param accessPostName the accessPostName to set
	 */
	public void setAccessPostName(String accessPostName) {
		this.accessPostName = accessPostName;
	}

	/**
	 * @return the sqlName
	 */
	public String getSqlName() {
		return sqlName;
	}

	/**
	 * @param sqlName the sqlName to set
	 */
	public void setSqlName(String sqlName) {
		this.sqlName = sqlName;
	}
}