package com.sales.model;

import java.util.Date;
import java.util.List;

public class SPerformancePlan extends Page{
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_performance_plan.plan_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private Integer planId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_performance_plan.cycle_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private Integer cycleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_performance_plan.name
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_performance_plan.suitable_post_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private Integer suitablePostId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_performance_plan.post_type
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private Integer postType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_performance_plan.user_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_performance_plan.create_time
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private Date createTime;
    
    private List<SPerformanceItem> itemList;
    
    private List<SPlanItem> planItemList;
    
    private String cycleName;
    
    private String postTypeName;
    
    private String suitablePostName;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_performance_plan.plan_id
     *
     * @return the value of s_performance_plan.plan_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_performance_plan.plan_id
     *
     * @param planId the value for s_performance_plan.plan_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_performance_plan.cycle_id
     *
     * @return the value of s_performance_plan.cycle_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public Integer getCycleId() {
        return cycleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_performance_plan.cycle_id
     *
     * @param cycleId the value for s_performance_plan.cycle_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setCycleId(Integer cycleId) {
        this.cycleId = cycleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_performance_plan.name
     *
     * @return the value of s_performance_plan.name
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_performance_plan.name
     *
     * @param name the value for s_performance_plan.name
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_performance_plan.suitable_post_id
     *
     * @return the value of s_performance_plan.suitable_post_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public Integer getSuitablePostId() {
        return suitablePostId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_performance_plan.suitable_post_id
     *
     * @param suitablePostId the value for s_performance_plan.suitable_post_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setSuitablePostId(Integer suitablePostId) {
        this.suitablePostId = suitablePostId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_performance_plan.post_type
     *
     * @return the value of s_performance_plan.post_type
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public Integer getPostType() {
        return postType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_performance_plan.post_type
     *
     * @param postType the value for s_performance_plan.post_type
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setPostType(Integer postType) {
        this.postType = postType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_performance_plan.user_id
     *
     * @return the value of s_performance_plan.user_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_performance_plan.user_id
     *
     * @param userId the value for s_performance_plan.user_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_performance_plan.create_time
     *
     * @return the value of s_performance_plan.create_time
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_performance_plan.create_time
     *
     * @param createTime the value for s_performance_plan.create_time
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	/**
	 * @return the itemList
	 */
	public List<SPerformanceItem> getItemList() {
		return itemList;
	}

	/**
	 * @param itemList the itemList to set
	 */
	public void setItemList(List<SPerformanceItem> itemList) {
		this.itemList = itemList;
	}

	/**
	 * @return the planItemList
	 */
	public List<SPlanItem> getPlanItemList() {
		return planItemList;
	}

	/**
	 * @param planItemList the planItemList to set
	 */
	public void setPlanItemList(List<SPlanItem> planItemList) {
		this.planItemList = planItemList;
	}

	/**
	 * @return the cycleName
	 */
	public String getCycleName() {
		if (this.cycleId == null) {
			this.cycleName = "";
		}else if (this.cycleId.intValue() == 1) {
			this.cycleName = "月度考核";
		}else if (this.cycleId.intValue() == 2) {
			this.cycleName = "季度考核";
		}else if (this.cycleId.intValue() == 3) {
			this.cycleName = "年度考核";
		} else {
			this.cycleName = "";
		}
		return cycleName;
	}

	/**
	 * @return the postTypeName
	 */
	public String getPostTypeName() {
		if (this.postType == null) {
			this.postTypeName = "";
		}else if (this.postType.intValue() == 1) {
			this.postTypeName = "行政岗位";
		}else if (this.postType.intValue() == 2) {
			this.postTypeName = "业务岗位";
		}else {
			this.postTypeName = "";
		}
		return postTypeName;
	}

	/**
	 * @return the suitablePostName
	 */
	public String getSuitablePostName() {
		return suitablePostName;
	}

	/**
	 * @param suitablePostName the suitablePostName to set
	 */
	public void setSuitablePostName(String suitablePostName) {
		this.suitablePostName = suitablePostName;
	}

	
}