package com.sales.model;

public class SPlanItem {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_plan_item.plan_item_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private Integer planItemId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_plan_item.plan_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private Integer planId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_plan_item.item_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private Integer itemId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_plan_item.specific_weight
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    private Integer specificWeight;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_plan_item.plan_item_id
     *
     * @return the value of s_plan_item.plan_item_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public Integer getPlanItemId() {
        return planItemId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_plan_item.plan_item_id
     *
     * @param planItemId the value for s_plan_item.plan_item_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setPlanItemId(Integer planItemId) {
        this.planItemId = planItemId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_plan_item.plan_id
     *
     * @return the value of s_plan_item.plan_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_plan_item.plan_id
     *
     * @param planId the value for s_plan_item.plan_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_plan_item.item_id
     *
     * @return the value of s_plan_item.item_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_plan_item.item_id
     *
     * @param itemId the value for s_plan_item.item_id
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_plan_item.specific_weight
     *
     * @return the value of s_plan_item.specific_weight
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public Integer getSpecificWeight() {
        return specificWeight;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_plan_item.specific_weight
     *
     * @param specificWeight the value for s_plan_item.specific_weight
     *
     * @abatorgenerated Wed May 15 09:36:54 CST 2013
     */
    public void setSpecificWeight(Integer specificWeight) {
        this.specificWeight = specificWeight;
    }
}