package com.sales.model;

public class SPlanStation {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_plan_station.plan_station_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer planStationId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_plan_station.plan_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer planId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_plan_station.station_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    private Integer stationId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_plan_station.plan_station_id
     *
     * @return the value of s_plan_station.plan_station_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getPlanStationId() {
        return planStationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_plan_station.plan_station_id
     *
     * @param planStationId the value for s_plan_station.plan_station_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setPlanStationId(Integer planStationId) {
        this.planStationId = planStationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_plan_station.plan_id
     *
     * @return the value of s_plan_station.plan_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_plan_station.plan_id
     *
     * @param planId the value for s_plan_station.plan_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_plan_station.station_id
     *
     * @return the value of s_plan_station.station_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public Integer getStationId() {
        return stationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_plan_station.station_id
     *
     * @param stationId the value for s_plan_station.station_id
     *
     * @abatorgenerated Tue Apr 23 17:36:30 CST 2013
     */
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }
}