package com.sales.model;

public class SRole {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_role.role_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer roleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_role.name
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_role.comment
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String comment;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_role.status
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer status;
    private String isSelect;
    
    /**
     * 是否检查客户使用权限
     */
    private Boolean customerChecked;

    public String getIsSelect() {
		return isSelect;
	}

	public void setIsSelect(String isSelect) {
		this.isSelect = isSelect;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_role.role_id
     *
     * @return the value of s_role.role_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_role.role_id
     *
     * @param roleId the value for s_role.role_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_role.name
     *
     * @return the value of s_role.name
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_role.name
     *
     * @param name the value for s_role.name
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_role.comment
     *
     * @return the value of s_role.comment
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_role.comment
     *
     * @param comment the value for s_role.comment
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_role.status
     *
     * @return the value of s_role.status
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_role.status
     *
     * @param status the value for s_role.status
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public Boolean getCustomerChecked() {
		return customerChecked;
	}

	public void setCustomerChecked(Boolean customerChecked) {
		this.customerChecked = customerChecked;
	}
}