package com.sales.model;

public class SRoleAction {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_role_action.role_action_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer roleActionId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_role_action.role_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer roleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_role_action.action_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer actionId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_role_action.method
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String method;
    
    private String actionName;
    
    private String url;

    public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getActionName() {
		return actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_role_action.role_action_id
     *
     * @return the value of s_role_action.role_action_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getRoleActionId() {
        return roleActionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_role_action.role_action_id
     *
     * @param roleActionId the value for s_role_action.role_action_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setRoleActionId(Integer roleActionId) {
        this.roleActionId = roleActionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_role_action.role_id
     *
     * @return the value of s_role_action.role_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_role_action.role_id
     *
     * @param roleId the value for s_role_action.role_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_role_action.action_id
     *
     * @return the value of s_role_action.action_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getActionId() {
        return actionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_role_action.action_id
     *
     * @param actionId the value for s_role_action.action_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_role_action.method
     *
     * @return the value of s_role_action.method
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_role_action.method
     *
     * @param method the value for s_role_action.method
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setMethod(String method) {
        this.method = method;
    }
}