package com.sales.model;

import java.sql.Timestamp;
import java.util.Date;

import com.sales.common.DisplayAnnotation;
import com.sales.common.NormalFun;

public class SSalesActivity extends BaseObject{
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_sales_activity.activity_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer activityId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_sales_activity.topical
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    @DisplayAnnotation(name="活动主题")
    private String topical;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_sales_activity.project_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer projectId;
    
    private String projectTopical;

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_sales_activity.customer_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer customerId;
    
    @DisplayAnnotation(name="客户名：")
    private String customerName;

    public String getCustomerName() {
    		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_sales_activity.activity_date
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
	@DisplayAnnotation(name="活动日期")
    private Timestamp activityDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_sales_activity.response_user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer responseUserId;
    
    private String responseUserName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_sales_activity.comment
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    @DisplayAnnotation(name="活动内容")
    private String comment;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_sales_activity.completion_rate
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String completionRate;
    
    @DisplayAnnotation(name="拜访人")
    private String visitPerson;
    
    private String coordinationVisitPerson;
    
    private String startTime;
    
    private String endTime;
    
    private Integer enumerationId;
    
    private String enumerationName;
    
    private Integer customerProjectId;
    
    private String customerProjectName;
    
    
    /**	活动填写的地理位置相关信息	*/
    private String locLatitude;		//经度
    private String locLongitude;	//维度
    @DisplayAnnotation(name="签到地址")
    private String locAddress;		//地址文本信息

    public Integer getCustomerProjectId() {
		return customerProjectId;
	}

	public void setCustomerProjectId(Integer customerProjectId) {
		this.customerProjectId = customerProjectId;
	}

	public String getCustomerProjectName() {
		return customerProjectName;
	}

	public void setCustomerProjectName(String customerProjectName) {
		this.customerProjectName = customerProjectName;
	}

	public Integer getEnumerationId() {
		return enumerationId;
	}

	public void setEnumerationId(Integer enumerationId) {
		this.enumerationId = enumerationId;
	}

	public String getEnumerationName() {
		return enumerationName;
	}

	public void setEnumerationName(String enumerationName) {
		this.enumerationName = enumerationName;
	}

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getVisitPerson() {
		return visitPerson;
	}

	public void setVisitPerson(String visitPerson) {
		this.visitPerson = visitPerson;
	}

	public String getCoordinationVisitPerson() {
		return coordinationVisitPerson;
	}

	public void setCoordinationVisitPerson(String coordinationVisitPerson) {
		this.coordinationVisitPerson = coordinationVisitPerson;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_sales_activity.activity_id
     *
     * @return the value of s_sales_activity.activity_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_sales_activity.activity_id
     *
     * @param activityId the value for s_sales_activity.activity_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_sales_activity.topical
     *
     * @return the value of s_sales_activity.topical
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getTopical() {
        return topical;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_sales_activity.topical
     *
     * @param topical the value for s_sales_activity.topical
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setTopical(String topical) {
        this.topical = topical;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_sales_activity.project_id
     *
     * @return the value of s_sales_activity.project_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_sales_activity.project_id
     *
     * @param projectId the value for s_sales_activity.project_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    public String getProjectTopical() {
		return projectTopical;
	}

	public void setProjectTopical(String projectTopical) {
		this.projectTopical = projectTopical;
	}

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_sales_activity.customer_id
     *
     * @return the value of s_sales_activity.customer_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_sales_activity.customer_id
     *
     * @param customerId the value for s_sales_activity.customer_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_sales_activity.activity_date
     *
     * @return the value of s_sales_activity.activity_date
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Timestamp getActivityDate() {
        return activityDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_sales_activity.activity_date
     *
     * @param activityDate the value for s_sales_activity.activity_date
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setActivityDate(Timestamp activityDate) {
        this.activityDate = activityDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_sales_activity.response_user_id
     *
     * @return the value of s_sales_activity.response_user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getResponseUserId() {
        return responseUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_sales_activity.response_user_id
     *
     * @param responseUserId the value for s_sales_activity.response_user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setResponseUserId(Integer responseUserId) {
        this.responseUserId = responseUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_sales_activity.comment
     *
     * @return the value of s_sales_activity.comment
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_sales_activity.comment
     *
     * @param comment the value for s_sales_activity.comment
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_sales_activity.completion_rate
     *
     * @return the value of s_sales_activity.completion_rate
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getCompletionRate() {
        return completionRate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_sales_activity.completion_rate
     *
     * @param completionRate the value for s_sales_activity.completion_rate
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setCompletionRate(String completionRate) {
        this.completionRate = completionRate;
    }

	public String getResponseUserName() {
		return responseUserName;
	}

	public void setResponseUserName(String responseUserName) {
		this.responseUserName = responseUserName;
	}

	/**
	 * @return the locLatitude
	 */
	public String getLocLatitude() {
		return locLatitude;
	}

	/**
	 * @param locLatitude the locLatitude to set
	 */
	public void setLocLatitude(String locLatitude) {
		this.locLatitude = locLatitude;
	}

	/**
	 * @return the locLongitude
	 */
	public String getLocLongitude() {
		return locLongitude;
	}

	/**
	 * @param locLongitude the locLongitude to set
	 */
	public void setLocLongitude(String locLongitude) {
		this.locLongitude = locLongitude;
	}

	/**
	 * @return the locAddress
	 */
	public String getLocAddress() {
		return locAddress;
	}

	/**
	 * @param locAddress the locAddress to set
	 */
	public void setLocAddress(String locAddress) {
		this.locAddress = locAddress;
	}
	
	
	
	public String getActivityDateString() {
		return NormalFun.formatDateTimeString(activityDate);
	}
}