package com.sales.model;

import java.util.Date;

public class STraining {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_training.training_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer trainingId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_training.title
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String title;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_training.training_time
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Date trainingTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_training.training_content
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String trainingContent;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_training.assess
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String assess;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_training.feedback
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String feedback;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_training.attachment
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String attachment;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_training.training_id
     *
     * @return the value of s_training.training_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getTrainingId() {
        return trainingId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_training.training_id
     *
     * @param trainingId the value for s_training.training_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setTrainingId(Integer trainingId) {
        this.trainingId = trainingId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_training.title
     *
     * @return the value of s_training.title
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_training.title
     *
     * @param title the value for s_training.title
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_training.training_time
     *
     * @return the value of s_training.training_time
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Date getTrainingTime() {
        return trainingTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_training.training_time
     *
     * @param trainingTime the value for s_training.training_time
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setTrainingTime(Date trainingTime) {
        this.trainingTime = trainingTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_training.training_content
     *
     * @return the value of s_training.training_content
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getTrainingContent() {
        return trainingContent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_training.training_content
     *
     * @param trainingContent the value for s_training.training_content
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setTrainingContent(String trainingContent) {
        this.trainingContent = trainingContent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_training.assess
     *
     * @return the value of s_training.assess
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getAssess() {
        return assess;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_training.assess
     *
     * @param assess the value for s_training.assess
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setAssess(String assess) {
        this.assess = assess;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_training.feedback
     *
     * @return the value of s_training.feedback
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getFeedback() {
        return feedback;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_training.feedback
     *
     * @param feedback the value for s_training.feedback
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_training.attachment
     *
     * @return the value of s_training.attachment
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_training.attachment
     *
     * @param attachment the value for s_training.attachment
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }
}