package com.sales.model;

import java.util.Date;

import com.sales.common.DisplayAnnotation;

public class STripApplication extends Page {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_application.trip_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer tripId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_application.user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_application.trip_location
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    @DisplayAnnotation(name="出差地点")
    private String tripLocation;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_application.trip_comment
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    @DisplayAnnotation(name="申请备注")
    private String tripComment;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_application.start_time
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    @DisplayAnnotation(name="开始日期")
    private Date startTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_application.end_time
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    @DisplayAnnotation(name="结束日期")
    private Date endTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_application.agent
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String agent;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_application.status
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_application.trip_time
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    @DisplayAnnotation(name="申请时间")
    private Date tripTime;
    
    private String tripCode;
    
    @DisplayAnnotation(name="申请人")
    private String userName;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_application.trip_id
     *
     * @return the value of s_trip_application.trip_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getTripId() {
        return tripId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_application.trip_id
     *
     * @param tripId the value for s_trip_application.trip_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setTripId(Integer tripId) {
        this.tripId = tripId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_application.user_id
     *
     * @return the value of s_trip_application.user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_application.user_id
     *
     * @param userId the value for s_trip_application.user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_application.trip_location
     *
     * @return the value of s_trip_application.trip_location
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getTripLocation() {
        return tripLocation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_application.trip_location
     *
     * @param tripLocation the value for s_trip_application.trip_location
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setTripLocation(String tripLocation) {
        this.tripLocation = tripLocation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_application.trip_comment
     *
     * @return the value of s_trip_application.trip_comment
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getTripComment() {
        return tripComment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_application.trip_comment
     *
     * @param tripComment the value for s_trip_application.trip_comment
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setTripComment(String tripComment) {
        this.tripComment = tripComment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_application.start_time
     *
     * @return the value of s_trip_application.start_time
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_application.start_time
     *
     * @param startTime the value for s_trip_application.start_time
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_application.end_time
     *
     * @return the value of s_trip_application.end_time
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_application.end_time
     *
     * @param endTime the value for s_trip_application.end_time
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_application.agent
     *
     * @return the value of s_trip_application.agent
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_application.agent
     *
     * @param agent the value for s_trip_application.agent
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setAgent(String agent) {
        this.agent = agent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_application.status
     *
     * @return the value of s_trip_application.status
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_application.status
     *
     * @param status the value for s_trip_application.status
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_application.trip_time
     *
     * @return the value of s_trip_application.trip_time
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Date getTripTime() {
        return tripTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_application.trip_time
     *
     * @param tripTime the value for s_trip_application.trip_time
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setTripTime(Date tripTime) {
        this.tripTime = tripTime;
    }

	/**
	 * @return the tripCode
	 */
	public String getTripCode() {
		return tripCode;
	}

	/**
	 * @param tripCode the tripCode to set
	 */
	public void setTripCode(String tripCode) {
		this.tripCode = tripCode;
	}

	/**
	 * @return the userName
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * @param userName the userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}
}