package com.sales.model;

import java.util.Date;

public class STripExpense {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_expense.trip_expense_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer tripExpenseId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_expense.expense_sum
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Float expenseSum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_expense.expense_time
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Date expenseTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_expense.expense_comment
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String expenseComment;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_expense.uppercase
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String uppercase;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_expense.trip_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer tripId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_expense.status
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_trip_expense.trip_expense_code
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String tripExpenseCode;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_expense.trip_expense_id
     *
     * @return the value of s_trip_expense.trip_expense_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getTripExpenseId() {
        return tripExpenseId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_expense.trip_expense_id
     *
     * @param tripExpenseId the value for s_trip_expense.trip_expense_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setTripExpenseId(Integer tripExpenseId) {
        this.tripExpenseId = tripExpenseId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_expense.expense_sum
     *
     * @return the value of s_trip_expense.expense_sum
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Float getExpenseSum() {
        return expenseSum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_expense.expense_sum
     *
     * @param expenseSum the value for s_trip_expense.expense_sum
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setExpenseSum(Float expenseSum) {
        this.expenseSum = expenseSum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_expense.expense_time
     *
     * @return the value of s_trip_expense.expense_time
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Date getExpenseTime() {
        return expenseTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_expense.expense_time
     *
     * @param expenseTime the value for s_trip_expense.expense_time
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setExpenseTime(Date expenseTime) {
        this.expenseTime = expenseTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_expense.expense_comment
     *
     * @return the value of s_trip_expense.expense_comment
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getExpenseComment() {
        return expenseComment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_expense.expense_comment
     *
     * @param expenseComment the value for s_trip_expense.expense_comment
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setExpenseComment(String expenseComment) {
        this.expenseComment = expenseComment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_expense.uppercase
     *
     * @return the value of s_trip_expense.uppercase
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getUppercase() {
        return uppercase;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_expense.uppercase
     *
     * @param uppercase the value for s_trip_expense.uppercase
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setUppercase(String uppercase) {
        this.uppercase = uppercase;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_expense.trip_id
     *
     * @return the value of s_trip_expense.trip_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getTripId() {
        return tripId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_expense.trip_id
     *
     * @param tripId the value for s_trip_expense.trip_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setTripId(Integer tripId) {
        this.tripId = tripId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_expense.status
     *
     * @return the value of s_trip_expense.status
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_expense.status
     *
     * @param status the value for s_trip_expense.status
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_trip_expense.trip_expense_code
     *
     * @return the value of s_trip_expense.trip_expense_code
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getTripExpenseCode() {
        return tripExpenseCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_trip_expense.trip_expense_code
     *
     * @param tripExpenseCode the value for s_trip_expense.trip_expense_code
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setTripExpenseCode(String tripExpenseCode) {
        this.tripExpenseCode = tripExpenseCode;
    }
}