package com.sales.model;

import java.util.Date;
import java.util.List;

public class SUserPerformancePlan extends Page {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s 
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    private Integer performancePlanId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user_performance_plan.user_id
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user_performance_plan.year
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    private Integer year;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user_performance_plan.season
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    private Integer season;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user_performance_plan.month
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    private Integer month;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user_performance_plan.create_user_id
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    private Integer createUserId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user_performance_plan.create_time
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user_performance_plan.total_score
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    private Integer totalScore;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user_performance_plan.plan_id
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    private Integer planId;
    
    private String userName;
    
    private SPerformancePlan plan;
    
    private List<SUserPerformanceItem> userItemList;
    
    private Integer status;
    
    private String statusName;
    
    private String userIds;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user_performance_plan.performance_plan_id
     *
     * @return the value of s_user_performance_plan.performance_plan_id
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    public Integer getPerformancePlanId() {
        return performancePlanId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user_performance_plan.performance_plan_id
     *
     * @param performancePlanId the value for s_user_performance_plan.performance_plan_id
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    public void setPerformancePlanId(Integer performancePlanId) {
        this.performancePlanId = performancePlanId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user_performance_plan.user_id
     *
     * @return the value of s_user_performance_plan.user_id
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user_performance_plan.user_id
     *
     * @param userId the value for s_user_performance_plan.user_id
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user_performance_plan.year
     *
     * @return the value of s_user_performance_plan.year
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user_performance_plan.year
     *
     * @param year the value for s_user_performance_plan.year
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    public void setYear(Integer year) {
        this.year = year;
    }


    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user_performance_plan.month
     *
     * @return the value of s_user_performance_plan.month
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user_performance_plan.month
     *
     * @param month the value for s_user_performance_plan.month
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user_performance_plan.create_user_id
     *
     * @return the value of s_user_performance_plan.create_user_id
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user_performance_plan.create_user_id
     *
     * @param createUserId the value for s_user_performance_plan.create_user_id
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user_performance_plan.create_time
     *
     * @return the value of s_user_performance_plan.create_time
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user_performance_plan.create_time
     *
     * @param createTime the value for s_user_performance_plan.create_time
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user_performance_plan.total_score
     *
     * @return the value of s_user_performance_plan.total_score
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    public Integer getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user_performance_plan.total_score
     *
     * @param totalScore the value for s_user_performance_plan.total_score
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    public void setTotalScore(Integer totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user_performance_plan.plan_id
     *
     * @return the value of s_user_performance_plan.plan_id
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user_performance_plan.plan_id
     *
     * @param planId the value for s_user_performance_plan.plan_id
     *
     * @abatorgenerated Wed May 15 09:36:55 CST 2013
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

	/**
	 * @return the season
	 */
	public Integer getSeason() {
		return season;
	}

	/**
	 * @param season the season to set
	 */
	public void setSeason(Integer season) {
		this.season = season;
	}

	/**
	 * @return the userName
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * @param userName the userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * @return the plan
	 */
	public SPerformancePlan getPlan() {
		return plan;
	}

	/**
	 * @param plan the plan to set
	 */
	public void setPlan(SPerformancePlan plan) {
		this.plan = plan;
	}

	/**
	 * @return the userItemList
	 */
	public List<SUserPerformanceItem> getUserItemList() {
		return userItemList;
	}

	/**
	 * @param userItemList the userItemList to set
	 */
	public void setUserItemList(List<SUserPerformanceItem> userItemList) {
		this.userItemList = userItemList;
	}

	/**
	 * @return the status
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * @return the statusName
	 */
	public String getStatusName() {
		if (this.status == null) {
			return "";
		}
		if (this.status.intValue() == 0) {
			return "进行中";
		} else {
			return "已完成";
		}
	}

	/**
	 * @return the userIds
	 */
	public String getUserIds() {
		return userIds;
	}

	/**
	 * @param userIds the userIds to set
	 */
	public void setUserIds(String userIds) {
		this.userIds = userIds;
	}

	
}