package com.sales.model;

import java.util.List;

public class SUser extends BaseObject {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user.user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user.login_name
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String loginName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user.login_passwor
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String loginPasswor;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user.user_name
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String userName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user.mobile
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String mobile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user.phone
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String phone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user.email
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private String email;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user.status
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user.department_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer departmentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column s_user.role_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    private Integer roleId;
    
    private String roleName;
    

	private String departmentName;
    
    private Integer parentUserId;
    
    private String parentUserName;
    
    private Integer positionOrgId;
    private String positionName;
    private Integer positionBsId; 
    private String positionOrgName;
    private String positionBsName;
    private Integer k3UserId;
    private String k3UserName;
    public Integer getK3UserId() {
		return k3UserId;
	}

	public void setK3UserId(Integer k3UserId) {
		this.k3UserId = k3UserId;
	}

	public String getK3UserName() {
		return k3UserName;
	}

	public void setK3UserName(String k3UserName) {
		this.k3UserName = k3UserName;
	}

	public String getPositionOrgName() {
		return positionOrgName;
	}

	public void setPositionOrgName(String positionOrgName) {
		this.positionOrgName = positionOrgName;
	}

	public String getPositionBsName() {
		return positionBsName;
	}

	public void setPositionBsName(String positionBsName) {
		this.positionBsName = positionBsName;
	}

	public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	

	public Integer getPositionOrgId() {
		return positionOrgId;
	}

	public void setPositionOrgId(Integer positionOrgId) {
		this.positionOrgId = positionOrgId;
	}

	public String getPositionName() {
		return positionName;
	}

	public void setPositionName(String positionName) {
		this.positionName = positionName;
	}

	public Integer getPositionBsId() {
		return positionBsId;
	}

	public void setPositionBsId(Integer positionBsId) {
		this.positionBsId = positionBsId;
	}

	public Integer getParentUserId() {
		return parentUserId;
	}

	public void setParentUserId(Integer parentUserId) {
		this.parentUserId = parentUserId;
	}

	public String getParentUserName() {
		return parentUserName;
	}

	public void setParentUserName(String parentUserName) {
		this.parentUserName = parentUserName;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user.user_id
     *
     * @return the value of s_user.user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user.user_id
     *
     * @param userId the value for s_user.user_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user.login_name
     *
     * @return the value of s_user.login_name
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user.login_name
     *
     * @param loginName the value for s_user.login_name
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user.login_passwor
     *
     * @return the value of s_user.login_passwor
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getLoginPasswor() {
        return loginPasswor;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user.login_passwor
     *
     * @param loginPasswor the value for s_user.login_passwor
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setLoginPasswor(String loginPasswor) {
        this.loginPasswor = loginPasswor;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user.user_name
     *
     * @return the value of s_user.user_name
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user.user_name
     *
     * @param userName the value for s_user.user_name
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user.mobile
     *
     * @return the value of s_user.mobile
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user.mobile
     *
     * @param mobile the value for s_user.mobile
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user.phone
     *
     * @return the value of s_user.phone
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user.phone
     *
     * @param phone the value for s_user.phone
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user.email
     *
     * @return the value of s_user.email
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user.email
     *
     * @param email the value for s_user.email
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user.status
     *
     * @return the value of s_user.status
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user.status
     *
     * @param status the value for s_user.status
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user.department_id
     *
     * @return the value of s_user.department_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user.department_id
     *
     * @param departmentId the value for s_user.department_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column s_user.role_id
     *
     * @return the value of s_user.role_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column s_user.role_id
     *
     * @param roleId the value for s_user.role_id
     *
     * @abatorgenerated Tue Apr 23 17:36:31 CST 2013
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}